// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

#![allow(
    non_camel_case_types,
    unused,
    non_snake_case,
    clippy::needless_return,
    clippy::redundant_closure_call,
    clippy::redundant_closure,
    clippy::useless_conversion,
    clippy::unit_arg,
    clippy::unused_unit,
    clippy::double_parens,
    clippy::let_and_return,
    clippy::too_many_arguments,
    clippy::match_single_binding,
    clippy::clone_on_copy,
    clippy::let_unit_value,
    clippy::deref_addrof,
    clippy::explicit_auto_deref,
    clippy::borrow_deref_ref,
    clippy::needless_borrow
)]

// Section: imports

use flutter_rust_bridge::for_generated::byteorder::{NativeEndian, ReadBytesExt, WriteBytesExt};
use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
use flutter_rust_bridge::{Handler, IntoIntoDart};

// Section: boilerplate

flutter_rust_bridge::frb_generated_boilerplate!(
    default_stream_sink_codec = SseCodec,
    default_rust_opaque = RustOpaqueMoi,
    default_rust_auto_opaque = RustAutoOpaqueMoi,
);
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_VERSION: &str = "2.7.0";
pub(crate) const FLUTTER_RUST_BRIDGE_CODEGEN_CONTENT_HASH: i32 = 1039187493;

// Section: executor

flutter_rust_bridge::frb_generated_default_handler!();

// Section: wire_funcs

fn wire__crate__video__native_gateway__ffi_acquire_hls_playback_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_acquire_hls_playback",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_source_urls = <Vec<String>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::video::native_gateway::ffi_acquire_hls_playback(api_source_urls)
                                .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__broadcast_control__ffi_broadcast_event_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_broadcast_event",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_signed_event_json = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::broadcast_control::ffi_broadcast_event(
                            api_signed_event_json,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__feed_control__ffi_close_feed_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_close_feed",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_feed_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::feed_control::ffi_close_feed(api_feed_id).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__delivery_events_stream__ffi_delivery_events_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_delivery_events",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_sink = <StreamSink<
                crate::api::delivery_types::FfiDeliveryEvent,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::delivery_events_stream::ffi_delivery_events(api_sink)
                                .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__feed_updates_stream__ffi_feed_updates_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_feed_updates",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_feed_id = <String>::sse_decode(&mut deserializer);
            let api_sink = <StreamSink<
                crate::api::feed_types::FfiFeedUpdate,
                flutter_rust_bridge::for_generated::SseCodec,
            >>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::feed_updates_stream::ffi_feed_updates(
                            api_feed_id,
                            api_sink,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__video__native_gateway__ffi_get_discovered_videos_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_get_discovered_videos",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::video::native_gateway::ffi_get_discovered_videos().await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__feed_control__ffi_load_more_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_load_more",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_feed_id = <String>::sse_decode(&mut deserializer);
            let api_older_than_secs = <Option<u64>>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::feed_control::ffi_load_more(
                            api_feed_id,
                            api_older_than_secs,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__feed_control__ffi_open_feed_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_open_feed",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_spec = <crate::api::feed_types::FfiFeedSpec>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::feed_control::ffi_open_feed(api_spec).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__focus_control__ffi_playback_url_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_playback_url",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_item =
                <crate::api::delivery_types::FfiFocusItem>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok =
                            crate::api::focus_control::ffi_playback_url(api_item).await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__video__native_gateway__ffi_release_hls_playback_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_release_hls_playback",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_session_id = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, ()>(
                    (move || async move {
                        let output_ok = Result::<_, ()>::Ok(
                            crate::video::native_gateway::ffi_release_hls_playback(api_session_id)
                                .await,
                        )?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__engine_control__ffi_set_delivery_config_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_set_delivery_config",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_data_usage = <String>::sse_decode(&mut deserializer);
            let api_max_storage_bytes = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::engine_control::ffi_set_delivery_config(
                            api_data_usage,
                            api_max_storage_bytes,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__engine_control__ffi_start_engine_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_start_engine",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_cache_directory = <String>::sse_decode(&mut deserializer);
            let api_relay_urls = <String>::sse_decode(&mut deserializer);
            let api_data_usage = <String>::sse_decode(&mut deserializer);
            let api_max_storage_bytes = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::engine_control::ffi_start_engine(
                            api_cache_directory,
                            api_relay_urls,
                            api_data_usage,
                            api_max_storage_bytes,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__video__native_gateway__ffi_start_server_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_start_server",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_cache_directory = <String>::sse_decode(&mut deserializer);
            let api_max_parallel_downloads = <usize>::sse_decode(&mut deserializer);
            let api_max_storage_bytes = <u64>::sse_decode(&mut deserializer);
            let api_relay_urls = <String>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::video::native_gateway::ffi_start_server(
                            api_cache_directory,
                            api_max_parallel_downloads,
                            api_max_storage_bytes,
                            api_relay_urls,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__api__focus_control__ffi_update_focus_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_async::<flutter_rust_bridge::for_generated::SseCodec, _, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "ffi_update_focus",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            let api_feed_id = <String>::sse_decode(&mut deserializer);
            let api_items =
                <Vec<crate::api::delivery_types::FfiFocusItem>>::sse_decode(&mut deserializer);
            let api_current_index = <u32>::sse_decode(&mut deserializer);
            let api_watch_ms = <u64>::sse_decode(&mut deserializer);
            deserializer.end();
            move |context| async move {
                transform_result_sse::<_, flutter_rust_bridge::for_generated::anyhow::Error>(
                    (move || async move {
                        let output_ok = crate::api::focus_control::ffi_update_focus(
                            api_feed_id,
                            api_items,
                            api_current_index,
                            api_watch_ms,
                        )
                        .await?;
                        Ok(output_ok)
                    })()
                    .await,
                )
            }
        },
    )
}
fn wire__crate__video__native_gateway__init_app_impl(
    port_: flutter_rust_bridge::for_generated::MessagePort,
    ptr_: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len_: i32,
    data_len_: i32,
) {
    FLUTTER_RUST_BRIDGE_HANDLER.wrap_normal::<flutter_rust_bridge::for_generated::SseCodec, _, _>(
        flutter_rust_bridge::for_generated::TaskInfo {
            debug_name: "init_app",
            port: Some(port_),
            mode: flutter_rust_bridge::for_generated::FfiCallMode::Normal,
        },
        move || {
            let message = unsafe {
                flutter_rust_bridge::for_generated::Dart2RustMessageSse::from_wire(
                    ptr_,
                    rust_vec_len_,
                    data_len_,
                )
            };
            let mut deserializer =
                flutter_rust_bridge::for_generated::SseDeserializer::new(message);
            deserializer.end();
            move |context| {
                transform_result_sse::<_, ()>((move || {
                    let output_ok = Result::<_, ()>::Ok({
                        crate::video::native_gateway::init_app();
                    })?;
                    Ok(output_ok)
                })())
            }
        },
    )
}

// Section: dart2rust

impl SseDecode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return flutter_rust_bridge::for_generated::anyhow::anyhow!("{}", inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::delivery_types::FfiDeliveryEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode
    for StreamSink<
        crate::api::feed_types::FfiFeedUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <String>::sse_decode(deserializer);
        return StreamSink::deserialize(inner);
    }
}

impl SseDecode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <Vec<u8>>::sse_decode(deserializer);
        return String::from_utf8(inner).unwrap();
    }
}

impl SseDecode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap() != 0
    }
}

impl SseDecode for crate::api::delivery_types::FfiDeliveryEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_postId = <String>::sse_decode(deserializer);
        let mut var_kind =
            <crate::api::delivery_types::FfiDeliveryEventKind>::sse_decode(deserializer);
        let mut var_startable = <bool>::sse_decode(deserializer);
        let mut var_bytesPresent = <u64>::sse_decode(deserializer);
        let mut var_totalBytes = <Option<u64>>::sse_decode(deserializer);
        let mut var_detail = <Option<String>>::sse_decode(deserializer);
        return crate::api::delivery_types::FfiDeliveryEvent {
            post_id: var_postId,
            kind: var_kind,
            startable: var_startable,
            bytes_present: var_bytesPresent,
            total_bytes: var_totalBytes,
            detail: var_detail,
        };
    }
}

impl SseDecode for crate::api::delivery_types::FfiDeliveryEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::api::delivery_types::FfiDeliveryEventKind::Readiness,
            1 => crate::api::delivery_types::FfiDeliveryEventKind::Progress,
            2 => crate::api::delivery_types::FfiDeliveryEventKind::Error,
            _ => unreachable!("Invalid variant for FfiDeliveryEventKind: {}", inner),
        };
    }
}

impl SseDecode for crate::api::feed_types::FfiFeedCreator {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_pubkey = <String>::sse_decode(deserializer);
        let mut var_displayName = <String>::sse_decode(deserializer);
        let mut var_handle = <String>::sse_decode(deserializer);
        let mut var_avatarUrl = <Option<String>>::sse_decode(deserializer);
        return crate::api::feed_types::FfiFeedCreator {
            pubkey: var_pubkey,
            display_name: var_displayName,
            handle: var_handle,
            avatar_url: var_avatarUrl,
        };
    }
}

impl SseDecode for crate::api::feed_types::FfiFeedMedia {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_urls = <Vec<String>>::sse_decode(deserializer);
        let mut var_delivery = <String>::sse_decode(deserializer);
        let mut var_sha256 = <Option<String>>::sse_decode(deserializer);
        let mut var_sizeBytes = <Option<u64>>::sse_decode(deserializer);
        let mut var_durationMs = <Option<u64>>::sse_decode(deserializer);
        let mut var_dim = <Option<crate::api::feed_types::FfiMediaDim>>::sse_decode(deserializer);
        let mut var_blurhash = <Option<String>>::sse_decode(deserializer);
        let mut var_thumbUrl = <Option<String>>::sse_decode(deserializer);
        return crate::api::feed_types::FfiFeedMedia {
            urls: var_urls,
            delivery: var_delivery,
            sha256: var_sha256,
            size_bytes: var_sizeBytes,
            duration_ms: var_durationMs,
            dim: var_dim,
            blurhash: var_blurhash,
            thumb_url: var_thumbUrl,
        };
    }
}

impl SseDecode for crate::api::feed_types::FfiFeedPost {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_postId = <String>::sse_decode(deserializer);
        let mut var_eventId = <String>::sse_decode(deserializer);
        let mut var_createdAt = <u64>::sse_decode(deserializer);
        let mut var_caption = <String>::sse_decode(deserializer);
        let mut var_hashtags = <Vec<String>>::sse_decode(deserializer);
        let mut var_creator = <crate::api::feed_types::FfiFeedCreator>::sse_decode(deserializer);
        let mut var_media = <crate::api::feed_types::FfiFeedMedia>::sse_decode(deserializer);
        return crate::api::feed_types::FfiFeedPost {
            post_id: var_postId,
            event_id: var_eventId,
            created_at: var_createdAt,
            caption: var_caption,
            hashtags: var_hashtags,
            creator: var_creator,
            media: var_media,
        };
    }
}

impl SseDecode for crate::api::feed_types::FfiFeedSpec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_kind = <String>::sse_decode(deserializer);
        let mut var_value = <Option<String>>::sse_decode(deserializer);
        let mut var_viewerPubkey = <Option<String>>::sse_decode(deserializer);
        return crate::api::feed_types::FfiFeedSpec {
            kind: var_kind,
            value: var_value,
            viewer_pubkey: var_viewerPubkey,
        };
    }
}

impl SseDecode for crate::api::feed_types::FfiFeedUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_feedId = <String>::sse_decode(deserializer);
        let mut var_revision = <u64>::sse_decode(deserializer);
        let mut var_posts = <Vec<crate::api::feed_types::FfiFeedPost>>::sse_decode(deserializer);
        return crate::api::feed_types::FfiFeedUpdate {
            feed_id: var_feedId,
            revision: var_revision,
            posts: var_posts,
        };
    }
}

impl SseDecode for crate::api::delivery_types::FfiFocusItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_postId = <String>::sse_decode(deserializer);
        let mut var_urls = <Vec<String>>::sse_decode(deserializer);
        let mut var_delivery = <String>::sse_decode(deserializer);
        let mut var_sha256 = <Option<String>>::sse_decode(deserializer);
        let mut var_sizeBytes = <Option<u64>>::sse_decode(deserializer);
        let mut var_durationMs = <Option<u64>>::sse_decode(deserializer);
        return crate::api::delivery_types::FfiFocusItem {
            post_id: var_postId,
            urls: var_urls,
            delivery: var_delivery,
            sha256: var_sha256,
            size_bytes: var_sizeBytes,
            duration_ms: var_durationMs,
        };
    }
}

impl SseDecode for crate::video::ffi_models::FfiHlsPlaybackSession {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_sessionId = <String>::sse_decode(deserializer);
        let mut var_playbackUrl = <String>::sse_decode(deserializer);
        return crate::video::ffi_models::FfiHlsPlaybackSession {
            session_id: var_sessionId,
            playback_url: var_playbackUrl,
        };
    }
}

impl SseDecode for crate::api::feed_types::FfiMediaDim {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_width = <u32>::sse_decode(deserializer);
        let mut var_height = <u32>::sse_decode(deserializer);
        return crate::api::feed_types::FfiMediaDim {
            width: var_width,
            height: var_height,
        };
    }
}

impl SseDecode for crate::video::ffi_models::FfiNostrEventIdentity {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_eventId = <String>::sse_decode(deserializer);
        let mut var_authorPublicKeyHex = <String>::sse_decode(deserializer);
        let mut var_kind = <u64>::sse_decode(deserializer);
        let mut var_identifier = <Option<String>>::sse_decode(deserializer);
        let mut var_createdAt = <u64>::sse_decode(deserializer);
        let mut var_content = <String>::sse_decode(deserializer);
        let mut var_hashtags = <Vec<String>>::sse_decode(deserializer);
        return crate::video::ffi_models::FfiNostrEventIdentity {
            event_id: var_eventId,
            author_public_key_hex: var_authorPublicKeyHex,
            kind: var_kind,
            identifier: var_identifier,
            created_at: var_createdAt,
            content: var_content,
            hashtags: var_hashtags,
        };
    }
}

impl SseDecode for crate::video::ffi_models::FfiNostrVideo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_expectedDigest = <Option<String>>::sse_decode(deserializer);
        let mut var_fallbackUrls = <Vec<String>>::sse_decode(deserializer);
        let mut var_user = <crate::video::ffi_models::FfiUserData>::sse_decode(deserializer);
        let mut var_title = <String>::sse_decode(deserializer);
        let mut var_songName = <String>::sse_decode(deserializer);
        let mut var_likes = <String>::sse_decode(deserializer);
        let mut var_comments = <String>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_delivery =
            <crate::video::ffi_models::FfiVideoDelivery>::sse_decode(deserializer);
        return crate::video::ffi_models::FfiNostrVideo {
            id: var_id,
            expected_digest: var_expectedDigest,
            fallback_urls: var_fallbackUrls,
            user: var_user,
            title: var_title,
            song_name: var_songName,
            likes: var_likes,
            comments: var_comments,
            url: var_url,
            delivery: var_delivery,
        };
    }
}

impl SseDecode for crate::video::ffi_models::FfiUserData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_npub = <Option<String>>::sse_decode(deserializer);
        let mut var_name = <Option<String>>::sse_decode(deserializer);
        let mut var_profilePicture = <Option<String>>::sse_decode(deserializer);
        return crate::video::ffi_models::FfiUserData {
            npub: var_npub,
            name: var_name,
            profile_picture: var_profilePicture,
        };
    }
}

impl SseDecode for crate::video::ffi_models::FfiVideoDelivery {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut inner = <i32>::sse_decode(deserializer);
        return match inner {
            0 => crate::video::ffi_models::FfiVideoDelivery::Progressive,
            1 => crate::video::ffi_models::FfiVideoDelivery::Hls,
            _ => unreachable!("Invalid variant for FfiVideoDelivery: {}", inner),
        };
    }
}

impl SseDecode for crate::video::ffi_models::FfiVideoDownload {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut var_id = <String>::sse_decode(deserializer);
        let mut var_url = <String>::sse_decode(deserializer);
        let mut var_title = <Option<String>>::sse_decode(deserializer);
        let mut var_localPath = <Option<String>>::sse_decode(deserializer);
        let mut var_event =
            <crate::video::ffi_models::FfiNostrEventIdentity>::sse_decode(deserializer);
        let mut var_nostr = <crate::video::ffi_models::FfiNostrVideo>::sse_decode(deserializer);
        return crate::video::ffi_models::FfiVideoDownload {
            id: var_id,
            url: var_url,
            title: var_title,
            local_path: var_localPath,
            event: var_event,
            nostr: var_nostr,
        };
    }
}

impl SseDecode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_i32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<String>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::feed_types::FfiFeedPost> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::feed_types::FfiFeedPost>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::api::delivery_types::FfiFocusItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::api::delivery_types::FfiFocusItem>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<crate::video::ffi_models::FfiVideoDownload> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<crate::video::ffi_models::FfiVideoDownload>::sse_decode(
                deserializer,
            ));
        }
        return ans_;
    }
}

impl SseDecode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        let mut len_ = <i32>::sse_decode(deserializer);
        let mut ans_ = vec![];
        for idx_ in 0..len_ {
            ans_.push(<u8>::sse_decode(deserializer));
        }
        return ans_;
    }
}

impl SseDecode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<String>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<crate::api::feed_types::FfiMediaDim> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<crate::api::feed_types::FfiMediaDim>::sse_decode(
                deserializer,
            ));
        } else {
            return None;
        }
    }
}

impl SseDecode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        if (<bool>::sse_decode(deserializer)) {
            return Some(<u64>::sse_decode(deserializer));
        } else {
            return None;
        }
    }
}

impl SseDecode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u32::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap()
    }
}

impl SseDecode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u8().unwrap()
    }
}

impl SseDecode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {}
}

impl SseDecode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_decode(deserializer: &mut flutter_rust_bridge::for_generated::SseDeserializer) -> Self {
        deserializer.cursor.read_u64::<NativeEndian>().unwrap() as _
    }
}

fn pde_ffi_dispatcher_primary_impl(
    func_id: i32,
    port: flutter_rust_bridge::for_generated::MessagePort,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        3 => wire__crate__video__native_gateway__ffi_acquire_hls_playback_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        4 => wire__crate__api__broadcast_control__ffi_broadcast_event_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        5 => wire__crate__api__feed_control__ffi_close_feed_impl(port, ptr, rust_vec_len, data_len),
        6 => wire__crate__api__delivery_events_stream__ffi_delivery_events_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        7 => wire__crate__api__feed_updates_stream__ffi_feed_updates_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        8 => wire__crate__video__native_gateway__ffi_get_discovered_videos_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        9 => wire__crate__api__feed_control__ffi_load_more_impl(port, ptr, rust_vec_len, data_len),
        10 => wire__crate__api__feed_control__ffi_open_feed_impl(port, ptr, rust_vec_len, data_len),
        11 => wire__crate__api__focus_control__ffi_playback_url_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        12 => wire__crate__video__native_gateway__ffi_release_hls_playback_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        13 => wire__crate__api__engine_control__ffi_set_delivery_config_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        14 => wire__crate__api__engine_control__ffi_start_engine_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        15 => wire__crate__video__native_gateway__ffi_start_server_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        16 => wire__crate__api__focus_control__ffi_update_focus_impl(
            port,
            ptr,
            rust_vec_len,
            data_len,
        ),
        17 => wire__crate__video__native_gateway__init_app_impl(port, ptr, rust_vec_len, data_len),
        _ => unreachable!(),
    }
}

fn pde_ffi_dispatcher_sync_impl(
    func_id: i32,
    ptr: flutter_rust_bridge::for_generated::PlatformGeneralizedUint8ListPtr,
    rust_vec_len: i32,
    data_len: i32,
) -> flutter_rust_bridge::for_generated::WireSyncRust2DartSse {
    // Codec=Pde (Serialization + dispatch), see doc to use other codecs
    match func_id {
        _ => unreachable!(),
    }
}

// Section: rust2dart

// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::delivery_types::FfiDeliveryEvent {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.post_id.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.startable.into_into_dart().into_dart(),
            self.bytes_present.into_into_dart().into_dart(),
            self.total_bytes.into_into_dart().into_dart(),
            self.detail.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::delivery_types::FfiDeliveryEvent
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::delivery_types::FfiDeliveryEvent>
    for crate::api::delivery_types::FfiDeliveryEvent
{
    fn into_into_dart(self) -> crate::api::delivery_types::FfiDeliveryEvent {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::delivery_types::FfiDeliveryEventKind {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Readiness => 0.into_dart(),
            Self::Progress => 1.into_dart(),
            Self::Error => 2.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::delivery_types::FfiDeliveryEventKind
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::delivery_types::FfiDeliveryEventKind>
    for crate::api::delivery_types::FfiDeliveryEventKind
{
    fn into_into_dart(self) -> crate::api::delivery_types::FfiDeliveryEventKind {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::feed_types::FfiFeedCreator {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.pubkey.into_into_dart().into_dart(),
            self.display_name.into_into_dart().into_dart(),
            self.handle.into_into_dart().into_dart(),
            self.avatar_url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::feed_types::FfiFeedCreator
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::feed_types::FfiFeedCreator>
    for crate::api::feed_types::FfiFeedCreator
{
    fn into_into_dart(self) -> crate::api::feed_types::FfiFeedCreator {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::feed_types::FfiFeedMedia {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.urls.into_into_dart().into_dart(),
            self.delivery.into_into_dart().into_dart(),
            self.sha256.into_into_dart().into_dart(),
            self.size_bytes.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
            self.dim.into_into_dart().into_dart(),
            self.blurhash.into_into_dart().into_dart(),
            self.thumb_url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::feed_types::FfiFeedMedia
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::feed_types::FfiFeedMedia>
    for crate::api::feed_types::FfiFeedMedia
{
    fn into_into_dart(self) -> crate::api::feed_types::FfiFeedMedia {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::feed_types::FfiFeedPost {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.post_id.into_into_dart().into_dart(),
            self.event_id.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.caption.into_into_dart().into_dart(),
            self.hashtags.into_into_dart().into_dart(),
            self.creator.into_into_dart().into_dart(),
            self.media.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::feed_types::FfiFeedPost
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::feed_types::FfiFeedPost>
    for crate::api::feed_types::FfiFeedPost
{
    fn into_into_dart(self) -> crate::api::feed_types::FfiFeedPost {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::feed_types::FfiFeedSpec {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.kind.into_into_dart().into_dart(),
            self.value.into_into_dart().into_dart(),
            self.viewer_pubkey.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::feed_types::FfiFeedSpec
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::feed_types::FfiFeedSpec>
    for crate::api::feed_types::FfiFeedSpec
{
    fn into_into_dart(self) -> crate::api::feed_types::FfiFeedSpec {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::feed_types::FfiFeedUpdate {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.feed_id.into_into_dart().into_dart(),
            self.revision.into_into_dart().into_dart(),
            self.posts.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::feed_types::FfiFeedUpdate
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::feed_types::FfiFeedUpdate>
    for crate::api::feed_types::FfiFeedUpdate
{
    fn into_into_dart(self) -> crate::api::feed_types::FfiFeedUpdate {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::delivery_types::FfiFocusItem {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.post_id.into_into_dart().into_dart(),
            self.urls.into_into_dart().into_dart(),
            self.delivery.into_into_dart().into_dart(),
            self.sha256.into_into_dart().into_dart(),
            self.size_bytes.into_into_dart().into_dart(),
            self.duration_ms.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::delivery_types::FfiFocusItem
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::delivery_types::FfiFocusItem>
    for crate::api::delivery_types::FfiFocusItem
{
    fn into_into_dart(self) -> crate::api::delivery_types::FfiFocusItem {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::video::ffi_models::FfiHlsPlaybackSession {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.session_id.into_into_dart().into_dart(),
            self.playback_url.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::video::ffi_models::FfiHlsPlaybackSession
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::video::ffi_models::FfiHlsPlaybackSession>
    for crate::video::ffi_models::FfiHlsPlaybackSession
{
    fn into_into_dart(self) -> crate::video::ffi_models::FfiHlsPlaybackSession {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::api::feed_types::FfiMediaDim {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.width.into_into_dart().into_dart(),
            self.height.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::api::feed_types::FfiMediaDim
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::api::feed_types::FfiMediaDim>
    for crate::api::feed_types::FfiMediaDim
{
    fn into_into_dart(self) -> crate::api::feed_types::FfiMediaDim {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::video::ffi_models::FfiNostrEventIdentity {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.event_id.into_into_dart().into_dart(),
            self.author_public_key_hex.into_into_dart().into_dart(),
            self.kind.into_into_dart().into_dart(),
            self.identifier.into_into_dart().into_dart(),
            self.created_at.into_into_dart().into_dart(),
            self.content.into_into_dart().into_dart(),
            self.hashtags.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::video::ffi_models::FfiNostrEventIdentity
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::video::ffi_models::FfiNostrEventIdentity>
    for crate::video::ffi_models::FfiNostrEventIdentity
{
    fn into_into_dart(self) -> crate::video::ffi_models::FfiNostrEventIdentity {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::video::ffi_models::FfiNostrVideo {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.expected_digest.into_into_dart().into_dart(),
            self.fallback_urls.into_into_dart().into_dart(),
            self.user.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.song_name.into_into_dart().into_dart(),
            self.likes.into_into_dart().into_dart(),
            self.comments.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.delivery.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::video::ffi_models::FfiNostrVideo
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::video::ffi_models::FfiNostrVideo>
    for crate::video::ffi_models::FfiNostrVideo
{
    fn into_into_dart(self) -> crate::video::ffi_models::FfiNostrVideo {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::video::ffi_models::FfiUserData {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.npub.into_into_dart().into_dart(),
            self.name.into_into_dart().into_dart(),
            self.profile_picture.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::video::ffi_models::FfiUserData
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::video::ffi_models::FfiUserData>
    for crate::video::ffi_models::FfiUserData
{
    fn into_into_dart(self) -> crate::video::ffi_models::FfiUserData {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::video::ffi_models::FfiVideoDelivery {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        match self {
            Self::Progressive => 0.into_dart(),
            Self::Hls => 1.into_dart(),
            _ => unreachable!(),
        }
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::video::ffi_models::FfiVideoDelivery
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::video::ffi_models::FfiVideoDelivery>
    for crate::video::ffi_models::FfiVideoDelivery
{
    fn into_into_dart(self) -> crate::video::ffi_models::FfiVideoDelivery {
        self
    }
}
// Codec=Dco (DartCObject based), see doc to use other codecs
impl flutter_rust_bridge::IntoDart for crate::video::ffi_models::FfiVideoDownload {
    fn into_dart(self) -> flutter_rust_bridge::for_generated::DartAbi {
        [
            self.id.into_into_dart().into_dart(),
            self.url.into_into_dart().into_dart(),
            self.title.into_into_dart().into_dart(),
            self.local_path.into_into_dart().into_dart(),
            self.event.into_into_dart().into_dart(),
            self.nostr.into_into_dart().into_dart(),
        ]
        .into_dart()
    }
}
impl flutter_rust_bridge::for_generated::IntoDartExceptPrimitive
    for crate::video::ffi_models::FfiVideoDownload
{
}
impl flutter_rust_bridge::IntoIntoDart<crate::video::ffi_models::FfiVideoDownload>
    for crate::video::ffi_models::FfiVideoDownload
{
    fn into_into_dart(self) -> crate::video::ffi_models::FfiVideoDownload {
        self
    }
}

impl SseEncode for flutter_rust_bridge::for_generated::anyhow::Error {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(format!("{:?}", self), serializer);
    }
}

impl SseEncode
    for StreamSink<
        crate::api::delivery_types::FfiDeliveryEvent,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode
    for StreamSink<
        crate::api::feed_types::FfiFeedUpdate,
        flutter_rust_bridge::for_generated::SseCodec,
    >
{
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        unimplemented!("")
    }
}

impl SseEncode for String {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<u8>>::sse_encode(self.into_bytes(), serializer);
    }
}

impl SseEncode for bool {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self as _).unwrap();
    }
}

impl SseEncode for crate::api::delivery_types::FfiDeliveryEvent {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.post_id, serializer);
        <crate::api::delivery_types::FfiDeliveryEventKind>::sse_encode(self.kind, serializer);
        <bool>::sse_encode(self.startable, serializer);
        <u64>::sse_encode(self.bytes_present, serializer);
        <Option<u64>>::sse_encode(self.total_bytes, serializer);
        <Option<String>>::sse_encode(self.detail, serializer);
    }
}

impl SseEncode for crate::api::delivery_types::FfiDeliveryEventKind {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::api::delivery_types::FfiDeliveryEventKind::Readiness => 0,
                crate::api::delivery_types::FfiDeliveryEventKind::Progress => 1,
                crate::api::delivery_types::FfiDeliveryEventKind::Error => 2,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::api::feed_types::FfiFeedCreator {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.pubkey, serializer);
        <String>::sse_encode(self.display_name, serializer);
        <String>::sse_encode(self.handle, serializer);
        <Option<String>>::sse_encode(self.avatar_url, serializer);
    }
}

impl SseEncode for crate::api::feed_types::FfiFeedMedia {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Vec<String>>::sse_encode(self.urls, serializer);
        <String>::sse_encode(self.delivery, serializer);
        <Option<String>>::sse_encode(self.sha256, serializer);
        <Option<u64>>::sse_encode(self.size_bytes, serializer);
        <Option<u64>>::sse_encode(self.duration_ms, serializer);
        <Option<crate::api::feed_types::FfiMediaDim>>::sse_encode(self.dim, serializer);
        <Option<String>>::sse_encode(self.blurhash, serializer);
        <Option<String>>::sse_encode(self.thumb_url, serializer);
    }
}

impl SseEncode for crate::api::feed_types::FfiFeedPost {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.post_id, serializer);
        <String>::sse_encode(self.event_id, serializer);
        <u64>::sse_encode(self.created_at, serializer);
        <String>::sse_encode(self.caption, serializer);
        <Vec<String>>::sse_encode(self.hashtags, serializer);
        <crate::api::feed_types::FfiFeedCreator>::sse_encode(self.creator, serializer);
        <crate::api::feed_types::FfiFeedMedia>::sse_encode(self.media, serializer);
    }
}

impl SseEncode for crate::api::feed_types::FfiFeedSpec {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.value, serializer);
        <Option<String>>::sse_encode(self.viewer_pubkey, serializer);
    }
}

impl SseEncode for crate::api::feed_types::FfiFeedUpdate {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.feed_id, serializer);
        <u64>::sse_encode(self.revision, serializer);
        <Vec<crate::api::feed_types::FfiFeedPost>>::sse_encode(self.posts, serializer);
    }
}

impl SseEncode for crate::api::delivery_types::FfiFocusItem {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.post_id, serializer);
        <Vec<String>>::sse_encode(self.urls, serializer);
        <String>::sse_encode(self.delivery, serializer);
        <Option<String>>::sse_encode(self.sha256, serializer);
        <Option<u64>>::sse_encode(self.size_bytes, serializer);
        <Option<u64>>::sse_encode(self.duration_ms, serializer);
    }
}

impl SseEncode for crate::video::ffi_models::FfiHlsPlaybackSession {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.session_id, serializer);
        <String>::sse_encode(self.playback_url, serializer);
    }
}

impl SseEncode for crate::api::feed_types::FfiMediaDim {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <u32>::sse_encode(self.width, serializer);
        <u32>::sse_encode(self.height, serializer);
    }
}

impl SseEncode for crate::video::ffi_models::FfiNostrEventIdentity {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.event_id, serializer);
        <String>::sse_encode(self.author_public_key_hex, serializer);
        <u64>::sse_encode(self.kind, serializer);
        <Option<String>>::sse_encode(self.identifier, serializer);
        <u64>::sse_encode(self.created_at, serializer);
        <String>::sse_encode(self.content, serializer);
        <Vec<String>>::sse_encode(self.hashtags, serializer);
    }
}

impl SseEncode for crate::video::ffi_models::FfiNostrVideo {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <Option<String>>::sse_encode(self.expected_digest, serializer);
        <Vec<String>>::sse_encode(self.fallback_urls, serializer);
        <crate::video::ffi_models::FfiUserData>::sse_encode(self.user, serializer);
        <String>::sse_encode(self.title, serializer);
        <String>::sse_encode(self.song_name, serializer);
        <String>::sse_encode(self.likes, serializer);
        <String>::sse_encode(self.comments, serializer);
        <String>::sse_encode(self.url, serializer);
        <crate::video::ffi_models::FfiVideoDelivery>::sse_encode(self.delivery, serializer);
    }
}

impl SseEncode for crate::video::ffi_models::FfiUserData {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <Option<String>>::sse_encode(self.npub, serializer);
        <Option<String>>::sse_encode(self.name, serializer);
        <Option<String>>::sse_encode(self.profile_picture, serializer);
    }
}

impl SseEncode for crate::video::ffi_models::FfiVideoDelivery {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(
            match self {
                crate::video::ffi_models::FfiVideoDelivery::Progressive => 0,
                crate::video::ffi_models::FfiVideoDelivery::Hls => 1,
                _ => {
                    unimplemented!("");
                }
            },
            serializer,
        );
    }
}

impl SseEncode for crate::video::ffi_models::FfiVideoDownload {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <String>::sse_encode(self.id, serializer);
        <String>::sse_encode(self.url, serializer);
        <Option<String>>::sse_encode(self.title, serializer);
        <Option<String>>::sse_encode(self.local_path, serializer);
        <crate::video::ffi_models::FfiNostrEventIdentity>::sse_encode(self.event, serializer);
        <crate::video::ffi_models::FfiNostrVideo>::sse_encode(self.nostr, serializer);
    }
}

impl SseEncode for i32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_i32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for Vec<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <String>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::feed_types::FfiFeedPost> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::feed_types::FfiFeedPost>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::api::delivery_types::FfiFocusItem> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::api::delivery_types::FfiFocusItem>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<crate::video::ffi_models::FfiVideoDownload> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <crate::video::ffi_models::FfiVideoDownload>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Vec<u8> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <i32>::sse_encode(self.len() as _, serializer);
        for item in self {
            <u8>::sse_encode(item, serializer);
        }
    }
}

impl SseEncode for Option<String> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <String>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<crate::api::feed_types::FfiMediaDim> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <crate::api::feed_types::FfiMediaDim>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for Option<u64> {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        <bool>::sse_encode(self.is_some(), serializer);
        if let Some(value) = self {
            <u64>::sse_encode(value, serializer);
        }
    }
}

impl SseEncode for u32 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u32::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u64 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u64::<NativeEndian>(self).unwrap();
    }
}

impl SseEncode for u8 {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer.cursor.write_u8(self).unwrap();
    }
}

impl SseEncode for () {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {}
}

impl SseEncode for usize {
    // Codec=Sse (Serialization based), see doc to use other codecs
    fn sse_encode(self, serializer: &mut flutter_rust_bridge::for_generated::SseSerializer) {
        serializer
            .cursor
            .write_u64::<NativeEndian>(self as _)
            .unwrap();
    }
}

#[cfg(not(target_family = "wasm"))]
mod io {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.7.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_io!();
}
#[cfg(not(target_family = "wasm"))]
pub use io::*;

/// cbindgen:ignore
#[cfg(target_family = "wasm")]
mod web {
    // This file is automatically generated, so please do not edit it.
    // @generated by `flutter_rust_bridge`@ 2.7.0.

    // Section: imports

    use super::*;
    use flutter_rust_bridge::for_generated::byteorder::{
        NativeEndian, ReadBytesExt, WriteBytesExt,
    };
    use flutter_rust_bridge::for_generated::wasm_bindgen;
    use flutter_rust_bridge::for_generated::wasm_bindgen::prelude::*;
    use flutter_rust_bridge::for_generated::{transform_result_dco, Lifetimeable, Lockable};
    use flutter_rust_bridge::{Handler, IntoIntoDart};

    // Section: boilerplate

    flutter_rust_bridge::frb_generated_boilerplate_web!();
}
#[cfg(target_family = "wasm")]
pub use web::*;
