// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/broadcast_control.dart';
import 'api/delivery_events_stream.dart';
import 'api/delivery_types.dart';
import 'api/engine_control.dart';
import 'api/event_control.dart';
import 'api/event_types.dart';
import 'api/feed_control.dart';
import 'api/feed_types.dart';
import 'api/feed_updates_stream.dart';
import 'api/focus_control.dart';
import 'api/network_control.dart';
import 'api/playback_control.dart';
import 'api/playback_preparation_stream.dart';
import 'api/playback_types.dart';
import 'api/player_preparation_control.dart';
import 'api/session_control.dart';
import 'api/warp_evidence_control.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'video/ffi_models.dart';
import 'video/native_gateway.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<FfiDeliveryEvent> dco_decode_StreamSink_ffi_delivery_event_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<FfiFeedUpdate> dco_decode_StreamSink_ffi_feed_update_Sse(
    dynamic raw,
  );

  @protected
  RustStreamSink<FfiPlaybackPreparationPlan>
  dco_decode_StreamSink_ffi_playback_preparation_plan_Sse(dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  EventOut dco_decode_TraitDef_EventOut(dynamic raw);

  @protected
  FeedOut dco_decode_TraitDef_FeedOut(dynamic raw);

  @protected
  PreparationOut dco_decode_TraitDef_PreparationOut(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiDeliveryEvent dco_decode_box_autoadd_ffi_delivery_event(dynamic raw);

  @protected
  FfiDeliveryNetworkStatus dco_decode_box_autoadd_ffi_delivery_network_status(
    dynamic raw,
  );

  @protected
  FfiEngineConfiguration dco_decode_box_autoadd_ffi_engine_configuration(
    dynamic raw,
  );

  @protected
  FfiFeedRepost dco_decode_box_autoadd_ffi_feed_repost(dynamic raw);

  @protected
  FfiFeedSpec dco_decode_box_autoadd_ffi_feed_spec(dynamic raw);

  @protected
  FfiFeedUpdate dco_decode_box_autoadd_ffi_feed_update(dynamic raw);

  @protected
  FfiFocusItem dco_decode_box_autoadd_ffi_focus_item(dynamic raw);

  @protected
  FfiFocusUpdate dco_decode_box_autoadd_ffi_focus_update(dynamic raw);

  @protected
  FfiMediaDim dco_decode_box_autoadd_ffi_media_dim(dynamic raw);

  @protected
  FfiNostrEventFilter dco_decode_box_autoadd_ffi_nostr_event_filter(
    dynamic raw,
  );

  @protected
  FfiPlaybackObservation dco_decode_box_autoadd_ffi_playback_observation(
    dynamic raw,
  );

  @protected
  FfiPlaybackPreparationAsset
  dco_decode_box_autoadd_ffi_playback_preparation_asset(dynamic raw);

  @protected
  FfiPlaybackPreparationPlan
  dco_decode_box_autoadd_ffi_playback_preparation_plan(dynamic raw);

  @protected
  FfiPlaybackPresentation dco_decode_box_autoadd_ffi_playback_presentation(
    dynamic raw,
  );

  @protected
  FfiPlayerPreparationReport
  dco_decode_box_autoadd_ffi_player_preparation_report(dynamic raw);

  @protected
  FfiTransportRescue dco_decode_box_autoadd_ffi_transport_rescue(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  FfiDataUsageLevel dco_decode_ffi_data_usage_level(dynamic raw);

  @protected
  FfiDeliveryEvent dco_decode_ffi_delivery_event(dynamic raw);

  @protected
  FfiDeliveryEventKind dco_decode_ffi_delivery_event_kind(dynamic raw);

  @protected
  FfiDeliveryNetworkClass dco_decode_ffi_delivery_network_class(dynamic raw);

  @protected
  FfiDeliveryNetworkStatus dco_decode_ffi_delivery_network_status(dynamic raw);

  @protected
  FfiEngineConfiguration dco_decode_ffi_engine_configuration(dynamic raw);

  @protected
  FfiFeedCreator dco_decode_ffi_feed_creator(dynamic raw);

  @protected
  FfiFeedKind dco_decode_ffi_feed_kind(dynamic raw);

  @protected
  FfiFeedMedia dco_decode_ffi_feed_media(dynamic raw);

  @protected
  FfiFeedPost dco_decode_ffi_feed_post(dynamic raw);

  @protected
  FfiFeedRepost dco_decode_ffi_feed_repost(dynamic raw);

  @protected
  FfiFeedRepostTarget dco_decode_ffi_feed_repost_target(dynamic raw);

  @protected
  FfiFeedSpec dco_decode_ffi_feed_spec(dynamic raw);

  @protected
  FfiFeedStage dco_decode_ffi_feed_stage(dynamic raw);

  @protected
  FfiFeedUpdate dco_decode_ffi_feed_update(dynamic raw);

  @protected
  FfiFocusItem dco_decode_ffi_focus_item(dynamic raw);

  @protected
  FfiFocusTransition dco_decode_ffi_focus_transition(dynamic raw);

  @protected
  FfiFocusUpdate dco_decode_ffi_focus_update(dynamic raw);

  @protected
  FfiHlsPlaybackSession dco_decode_ffi_hls_playback_session(dynamic raw);

  @protected
  FfiMediaDelivery dco_decode_ffi_media_delivery(dynamic raw);

  @protected
  FfiMediaDim dco_decode_ffi_media_dim(dynamic raw);

  @protected
  FfiNostrEvent dco_decode_ffi_nostr_event(dynamic raw);

  @protected
  FfiNostrEventFilter dco_decode_ffi_nostr_event_filter(dynamic raw);

  @protected
  FfiNostrTagFilter dco_decode_ffi_nostr_tag_filter(dynamic raw);

  @protected
  FfiPlaybackAdmissionSnapshot dco_decode_ffi_playback_admission_snapshot(
    dynamic raw,
  );

  @protected
  FfiPlaybackObservation dco_decode_ffi_playback_observation(dynamic raw);

  @protected
  FfiPlaybackPhase dco_decode_ffi_playback_phase(dynamic raw);

  @protected
  FfiPlaybackPreparationAsset dco_decode_ffi_playback_preparation_asset(
    dynamic raw,
  );

  @protected
  FfiPlaybackPreparationPlan dco_decode_ffi_playback_preparation_plan(
    dynamic raw,
  );

  @protected
  FfiPlaybackPreparationReadiness dco_decode_ffi_playback_preparation_readiness(
    dynamic raw,
  );

  @protected
  FfiPlaybackPresentation dco_decode_ffi_playback_presentation(dynamic raw);

  @protected
  FfiPlayerPreparationDisposition dco_decode_ffi_player_preparation_disposition(
    dynamic raw,
  );

  @protected
  FfiPlayerPreparationReport dco_decode_ffi_player_preparation_report(
    dynamic raw,
  );

  @protected
  FfiPlayerPreparationState dco_decode_ffi_player_preparation_state(
    dynamic raw,
  );

  @protected
  FfiTransportRescue dco_decode_ffi_transport_rescue(dynamic raw);

  @protected
  FfiTransportRescueReason dco_decode_ffi_transport_rescue_reason(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FfiFeedPost> dco_decode_list_ffi_feed_post(dynamic raw);

  @protected
  List<FfiFocusItem> dco_decode_list_ffi_focus_item(dynamic raw);

  @protected
  List<FfiNostrEvent> dco_decode_list_ffi_nostr_event(dynamic raw);

  @protected
  List<FfiNostrEventFilter> dco_decode_list_ffi_nostr_event_filter(dynamic raw);

  @protected
  List<FfiNostrTagFilter> dco_decode_list_ffi_nostr_tag_filter(dynamic raw);

  @protected
  List<FfiPlaybackPreparationAsset>
  dco_decode_list_ffi_playback_preparation_asset(dynamic raw);

  @protected
  List<List<String>> dco_decode_list_list_String(dynamic raw);

  @protected
  Uint16List dco_decode_list_prim_u_16_strict(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  NostrSessionResetError dco_decode_nostr_session_reset_error(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FfiFeedRepost? dco_decode_opt_box_autoadd_ffi_feed_repost(dynamic raw);

  @protected
  FfiMediaDim? dco_decode_opt_box_autoadd_ffi_media_dim(dynamic raw);

  @protected
  FfiPlaybackPreparationAsset?
  dco_decode_opt_box_autoadd_ffi_playback_preparation_asset(dynamic raw);

  @protected
  FfiTransportRescue? dco_decode_opt_box_autoadd_ffi_transport_rescue(
    dynamic raw,
  );

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_u_16(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<FfiDeliveryEvent> sse_decode_StreamSink_ffi_delivery_event_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FfiFeedUpdate> sse_decode_StreamSink_ffi_feed_update_Sse(
    SseDeserializer deserializer,
  );

  @protected
  RustStreamSink<FfiPlaybackPreparationPlan>
  sse_decode_StreamSink_ffi_playback_preparation_plan_Sse(
    SseDeserializer deserializer,
  );

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiDeliveryEvent sse_decode_box_autoadd_ffi_delivery_event(
    SseDeserializer deserializer,
  );

  @protected
  FfiDeliveryNetworkStatus sse_decode_box_autoadd_ffi_delivery_network_status(
    SseDeserializer deserializer,
  );

  @protected
  FfiEngineConfiguration sse_decode_box_autoadd_ffi_engine_configuration(
    SseDeserializer deserializer,
  );

  @protected
  FfiFeedRepost sse_decode_box_autoadd_ffi_feed_repost(
    SseDeserializer deserializer,
  );

  @protected
  FfiFeedSpec sse_decode_box_autoadd_ffi_feed_spec(
    SseDeserializer deserializer,
  );

  @protected
  FfiFeedUpdate sse_decode_box_autoadd_ffi_feed_update(
    SseDeserializer deserializer,
  );

  @protected
  FfiFocusItem sse_decode_box_autoadd_ffi_focus_item(
    SseDeserializer deserializer,
  );

  @protected
  FfiFocusUpdate sse_decode_box_autoadd_ffi_focus_update(
    SseDeserializer deserializer,
  );

  @protected
  FfiMediaDim sse_decode_box_autoadd_ffi_media_dim(
    SseDeserializer deserializer,
  );

  @protected
  FfiNostrEventFilter sse_decode_box_autoadd_ffi_nostr_event_filter(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackObservation sse_decode_box_autoadd_ffi_playback_observation(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackPreparationAsset
  sse_decode_box_autoadd_ffi_playback_preparation_asset(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackPreparationPlan
  sse_decode_box_autoadd_ffi_playback_preparation_plan(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackPresentation sse_decode_box_autoadd_ffi_playback_presentation(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlayerPreparationReport
  sse_decode_box_autoadd_ffi_player_preparation_report(
    SseDeserializer deserializer,
  );

  @protected
  FfiTransportRescue sse_decode_box_autoadd_ffi_transport_rescue(
    SseDeserializer deserializer,
  );

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  FfiDataUsageLevel sse_decode_ffi_data_usage_level(
    SseDeserializer deserializer,
  );

  @protected
  FfiDeliveryEvent sse_decode_ffi_delivery_event(SseDeserializer deserializer);

  @protected
  FfiDeliveryEventKind sse_decode_ffi_delivery_event_kind(
    SseDeserializer deserializer,
  );

  @protected
  FfiDeliveryNetworkClass sse_decode_ffi_delivery_network_class(
    SseDeserializer deserializer,
  );

  @protected
  FfiDeliveryNetworkStatus sse_decode_ffi_delivery_network_status(
    SseDeserializer deserializer,
  );

  @protected
  FfiEngineConfiguration sse_decode_ffi_engine_configuration(
    SseDeserializer deserializer,
  );

  @protected
  FfiFeedCreator sse_decode_ffi_feed_creator(SseDeserializer deserializer);

  @protected
  FfiFeedKind sse_decode_ffi_feed_kind(SseDeserializer deserializer);

  @protected
  FfiFeedMedia sse_decode_ffi_feed_media(SseDeserializer deserializer);

  @protected
  FfiFeedPost sse_decode_ffi_feed_post(SseDeserializer deserializer);

  @protected
  FfiFeedRepost sse_decode_ffi_feed_repost(SseDeserializer deserializer);

  @protected
  FfiFeedRepostTarget sse_decode_ffi_feed_repost_target(
    SseDeserializer deserializer,
  );

  @protected
  FfiFeedSpec sse_decode_ffi_feed_spec(SseDeserializer deserializer);

  @protected
  FfiFeedStage sse_decode_ffi_feed_stage(SseDeserializer deserializer);

  @protected
  FfiFeedUpdate sse_decode_ffi_feed_update(SseDeserializer deserializer);

  @protected
  FfiFocusItem sse_decode_ffi_focus_item(SseDeserializer deserializer);

  @protected
  FfiFocusTransition sse_decode_ffi_focus_transition(
    SseDeserializer deserializer,
  );

  @protected
  FfiFocusUpdate sse_decode_ffi_focus_update(SseDeserializer deserializer);

  @protected
  FfiHlsPlaybackSession sse_decode_ffi_hls_playback_session(
    SseDeserializer deserializer,
  );

  @protected
  FfiMediaDelivery sse_decode_ffi_media_delivery(SseDeserializer deserializer);

  @protected
  FfiMediaDim sse_decode_ffi_media_dim(SseDeserializer deserializer);

  @protected
  FfiNostrEvent sse_decode_ffi_nostr_event(SseDeserializer deserializer);

  @protected
  FfiNostrEventFilter sse_decode_ffi_nostr_event_filter(
    SseDeserializer deserializer,
  );

  @protected
  FfiNostrTagFilter sse_decode_ffi_nostr_tag_filter(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackAdmissionSnapshot sse_decode_ffi_playback_admission_snapshot(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackObservation sse_decode_ffi_playback_observation(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackPhase sse_decode_ffi_playback_phase(SseDeserializer deserializer);

  @protected
  FfiPlaybackPreparationAsset sse_decode_ffi_playback_preparation_asset(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackPreparationPlan sse_decode_ffi_playback_preparation_plan(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackPreparationReadiness sse_decode_ffi_playback_preparation_readiness(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackPresentation sse_decode_ffi_playback_presentation(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlayerPreparationDisposition sse_decode_ffi_player_preparation_disposition(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlayerPreparationReport sse_decode_ffi_player_preparation_report(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlayerPreparationState sse_decode_ffi_player_preparation_state(
    SseDeserializer deserializer,
  );

  @protected
  FfiTransportRescue sse_decode_ffi_transport_rescue(
    SseDeserializer deserializer,
  );

  @protected
  FfiTransportRescueReason sse_decode_ffi_transport_rescue_reason(
    SseDeserializer deserializer,
  );

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FfiFeedPost> sse_decode_list_ffi_feed_post(SseDeserializer deserializer);

  @protected
  List<FfiFocusItem> sse_decode_list_ffi_focus_item(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiNostrEvent> sse_decode_list_ffi_nostr_event(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiNostrEventFilter> sse_decode_list_ffi_nostr_event_filter(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiNostrTagFilter> sse_decode_list_ffi_nostr_tag_filter(
    SseDeserializer deserializer,
  );

  @protected
  List<FfiPlaybackPreparationAsset>
  sse_decode_list_ffi_playback_preparation_asset(SseDeserializer deserializer);

  @protected
  List<List<String>> sse_decode_list_list_String(SseDeserializer deserializer);

  @protected
  Uint16List sse_decode_list_prim_u_16_strict(SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  NostrSessionResetError sse_decode_nostr_session_reset_error(
    SseDeserializer deserializer,
  );

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FfiFeedRepost? sse_decode_opt_box_autoadd_ffi_feed_repost(
    SseDeserializer deserializer,
  );

  @protected
  FfiMediaDim? sse_decode_opt_box_autoadd_ffi_media_dim(
    SseDeserializer deserializer,
  );

  @protected
  FfiPlaybackPreparationAsset?
  sse_decode_opt_box_autoadd_ffi_playback_preparation_asset(
    SseDeserializer deserializer,
  );

  @protected
  FfiTransportRescue? sse_decode_opt_box_autoadd_ffi_transport_rescue(
    SseDeserializer deserializer,
  );

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_16(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
    AnyhowException self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ffi_delivery_event_Sse(
    RustStreamSink<FfiDeliveryEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ffi_feed_update_Sse(
    RustStreamSink<FfiFeedUpdate> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_StreamSink_ffi_playback_preparation_plan_Sse(
    RustStreamSink<FfiPlaybackPreparationPlan> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_delivery_event(
    FfiDeliveryEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_delivery_network_status(
    FfiDeliveryNetworkStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_engine_configuration(
    FfiEngineConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_feed_repost(
    FfiFeedRepost self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_feed_spec(
    FfiFeedSpec self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_feed_update(
    FfiFeedUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_focus_item(
    FfiFocusItem self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_focus_update(
    FfiFocusUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_media_dim(
    FfiMediaDim self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_nostr_event_filter(
    FfiNostrEventFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_playback_observation(
    FfiPlaybackObservation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_playback_preparation_asset(
    FfiPlaybackPreparationAsset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_playback_preparation_plan(
    FfiPlaybackPreparationPlan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_playback_presentation(
    FfiPlaybackPresentation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_player_preparation_report(
    FfiPlayerPreparationReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_ffi_transport_rescue(
    FfiTransportRescue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_data_usage_level(
    FfiDataUsageLevel self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_delivery_event(
    FfiDeliveryEvent self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_delivery_event_kind(
    FfiDeliveryEventKind self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_delivery_network_class(
    FfiDeliveryNetworkClass self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_delivery_network_status(
    FfiDeliveryNetworkStatus self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_engine_configuration(
    FfiEngineConfiguration self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_feed_creator(
    FfiFeedCreator self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_feed_kind(FfiFeedKind self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_media(FfiFeedMedia self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_post(FfiFeedPost self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_repost(FfiFeedRepost self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_repost_target(
    FfiFeedRepostTarget self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_feed_spec(FfiFeedSpec self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_stage(FfiFeedStage self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_update(FfiFeedUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_focus_item(FfiFocusItem self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_focus_transition(
    FfiFocusTransition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_focus_update(
    FfiFocusUpdate self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_hls_playback_session(
    FfiHlsPlaybackSession self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_media_delivery(
    FfiMediaDelivery self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_media_dim(FfiMediaDim self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_nostr_event(FfiNostrEvent self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_nostr_event_filter(
    FfiNostrEventFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_nostr_tag_filter(
    FfiNostrTagFilter self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_playback_admission_snapshot(
    FfiPlaybackAdmissionSnapshot self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_playback_observation(
    FfiPlaybackObservation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_playback_phase(
    FfiPlaybackPhase self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_playback_preparation_asset(
    FfiPlaybackPreparationAsset self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_playback_preparation_plan(
    FfiPlaybackPreparationPlan self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_playback_preparation_readiness(
    FfiPlaybackPreparationReadiness self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_playback_presentation(
    FfiPlaybackPresentation self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_player_preparation_disposition(
    FfiPlayerPreparationDisposition self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_player_preparation_report(
    FfiPlayerPreparationReport self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_player_preparation_state(
    FfiPlayerPreparationState self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_transport_rescue(
    FfiTransportRescue self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_ffi_transport_rescue_reason(
    FfiTransportRescueReason self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_feed_post(
    List<FfiFeedPost> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_focus_item(
    List<FfiFocusItem> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_nostr_event(
    List<FfiNostrEvent> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_nostr_event_filter(
    List<FfiNostrEventFilter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_nostr_tag_filter(
    List<FfiNostrTagFilter> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_ffi_playback_preparation_asset(
    List<FfiPlaybackPreparationAsset> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_list_String(
    List<List<String>> self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_16_strict(
    Uint16List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_list_prim_u_8_strict(
    Uint8List self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_nostr_session_reset_error(
    NostrSessionResetError self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_feed_repost(
    FfiFeedRepost? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_media_dim(
    FfiMediaDim? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_playback_preparation_asset(
    FfiPlaybackPreparationAsset? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_ffi_transport_rescue(
    FfiTransportRescue? self,
    SseSerializer serializer,
  );

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
  _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
    : _lookup = dynamicLibrary.lookup;
}
