// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/broadcast_control.dart';
import 'api/delivery_events_stream.dart';
import 'api/delivery_types.dart';
import 'api/engine_control.dart';
import 'api/feed_control.dart';
import 'api/feed_types.dart';
import 'api/feed_updates_stream.dart';
import 'api/focus_control.dart';
import 'dart:async';
import 'dart:convert';
import 'dart:ffi' as ffi;
import 'frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated_io.dart';
import 'video/ffi_models.dart';
import 'video/native_gateway.dart';

abstract class RustLibApiImplPlatform extends BaseApiImpl<RustLibWire> {
  RustLibApiImplPlatform({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw);

  @protected
  RustStreamSink<FfiDeliveryEvent> dco_decode_StreamSink_ffi_delivery_event_Sse(
      dynamic raw);

  @protected
  RustStreamSink<FfiFeedUpdate> dco_decode_StreamSink_ffi_feed_update_Sse(
      dynamic raw);

  @protected
  String dco_decode_String(dynamic raw);

  @protected
  EventOut dco_decode_TraitDef_EventOut(dynamic raw);

  @protected
  FeedOut dco_decode_TraitDef_FeedOut(dynamic raw);

  @protected
  bool dco_decode_bool(dynamic raw);

  @protected
  FfiDeliveryEvent dco_decode_box_autoadd_ffi_delivery_event(dynamic raw);

  @protected
  FfiFeedSpec dco_decode_box_autoadd_ffi_feed_spec(dynamic raw);

  @protected
  FfiFeedUpdate dco_decode_box_autoadd_ffi_feed_update(dynamic raw);

  @protected
  FfiFocusItem dco_decode_box_autoadd_ffi_focus_item(dynamic raw);

  @protected
  FfiMediaDim dco_decode_box_autoadd_ffi_media_dim(dynamic raw);

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw);

  @protected
  FfiDeliveryEvent dco_decode_ffi_delivery_event(dynamic raw);

  @protected
  FfiDeliveryEventKind dco_decode_ffi_delivery_event_kind(dynamic raw);

  @protected
  FfiFeedCreator dco_decode_ffi_feed_creator(dynamic raw);

  @protected
  FfiFeedMedia dco_decode_ffi_feed_media(dynamic raw);

  @protected
  FfiFeedPost dco_decode_ffi_feed_post(dynamic raw);

  @protected
  FfiFeedSpec dco_decode_ffi_feed_spec(dynamic raw);

  @protected
  FfiFeedUpdate dco_decode_ffi_feed_update(dynamic raw);

  @protected
  FfiFocusItem dco_decode_ffi_focus_item(dynamic raw);

  @protected
  FfiHlsPlaybackSession dco_decode_ffi_hls_playback_session(dynamic raw);

  @protected
  FfiMediaDim dco_decode_ffi_media_dim(dynamic raw);

  @protected
  FfiNostrEventIdentity dco_decode_ffi_nostr_event_identity(dynamic raw);

  @protected
  FfiNostrVideo dco_decode_ffi_nostr_video(dynamic raw);

  @protected
  FfiUserData dco_decode_ffi_user_data(dynamic raw);

  @protected
  FfiVideoDelivery dco_decode_ffi_video_delivery(dynamic raw);

  @protected
  FfiVideoDownload dco_decode_ffi_video_download(dynamic raw);

  @protected
  int dco_decode_i_32(dynamic raw);

  @protected
  List<String> dco_decode_list_String(dynamic raw);

  @protected
  List<FfiFeedPost> dco_decode_list_ffi_feed_post(dynamic raw);

  @protected
  List<FfiFocusItem> dco_decode_list_ffi_focus_item(dynamic raw);

  @protected
  List<FfiVideoDownload> dco_decode_list_ffi_video_download(dynamic raw);

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw);

  @protected
  String? dco_decode_opt_String(dynamic raw);

  @protected
  FfiMediaDim? dco_decode_opt_box_autoadd_ffi_media_dim(dynamic raw);

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw);

  @protected
  int dco_decode_u_32(dynamic raw);

  @protected
  BigInt dco_decode_u_64(dynamic raw);

  @protected
  int dco_decode_u_8(dynamic raw);

  @protected
  void dco_decode_unit(dynamic raw);

  @protected
  BigInt dco_decode_usize(dynamic raw);

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer);

  @protected
  RustStreamSink<FfiDeliveryEvent> sse_decode_StreamSink_ffi_delivery_event_Sse(
      SseDeserializer deserializer);

  @protected
  RustStreamSink<FfiFeedUpdate> sse_decode_StreamSink_ffi_feed_update_Sse(
      SseDeserializer deserializer);

  @protected
  String sse_decode_String(SseDeserializer deserializer);

  @protected
  bool sse_decode_bool(SseDeserializer deserializer);

  @protected
  FfiDeliveryEvent sse_decode_box_autoadd_ffi_delivery_event(
      SseDeserializer deserializer);

  @protected
  FfiFeedSpec sse_decode_box_autoadd_ffi_feed_spec(
      SseDeserializer deserializer);

  @protected
  FfiFeedUpdate sse_decode_box_autoadd_ffi_feed_update(
      SseDeserializer deserializer);

  @protected
  FfiFocusItem sse_decode_box_autoadd_ffi_focus_item(
      SseDeserializer deserializer);

  @protected
  FfiMediaDim sse_decode_box_autoadd_ffi_media_dim(
      SseDeserializer deserializer);

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  FfiDeliveryEvent sse_decode_ffi_delivery_event(SseDeserializer deserializer);

  @protected
  FfiDeliveryEventKind sse_decode_ffi_delivery_event_kind(
      SseDeserializer deserializer);

  @protected
  FfiFeedCreator sse_decode_ffi_feed_creator(SseDeserializer deserializer);

  @protected
  FfiFeedMedia sse_decode_ffi_feed_media(SseDeserializer deserializer);

  @protected
  FfiFeedPost sse_decode_ffi_feed_post(SseDeserializer deserializer);

  @protected
  FfiFeedSpec sse_decode_ffi_feed_spec(SseDeserializer deserializer);

  @protected
  FfiFeedUpdate sse_decode_ffi_feed_update(SseDeserializer deserializer);

  @protected
  FfiFocusItem sse_decode_ffi_focus_item(SseDeserializer deserializer);

  @protected
  FfiHlsPlaybackSession sse_decode_ffi_hls_playback_session(
      SseDeserializer deserializer);

  @protected
  FfiMediaDim sse_decode_ffi_media_dim(SseDeserializer deserializer);

  @protected
  FfiNostrEventIdentity sse_decode_ffi_nostr_event_identity(
      SseDeserializer deserializer);

  @protected
  FfiNostrVideo sse_decode_ffi_nostr_video(SseDeserializer deserializer);

  @protected
  FfiUserData sse_decode_ffi_user_data(SseDeserializer deserializer);

  @protected
  FfiVideoDelivery sse_decode_ffi_video_delivery(SseDeserializer deserializer);

  @protected
  FfiVideoDownload sse_decode_ffi_video_download(SseDeserializer deserializer);

  @protected
  int sse_decode_i_32(SseDeserializer deserializer);

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer);

  @protected
  List<FfiFeedPost> sse_decode_list_ffi_feed_post(SseDeserializer deserializer);

  @protected
  List<FfiFocusItem> sse_decode_list_ffi_focus_item(
      SseDeserializer deserializer);

  @protected
  List<FfiVideoDownload> sse_decode_list_ffi_video_download(
      SseDeserializer deserializer);

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer);

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer);

  @protected
  FfiMediaDim? sse_decode_opt_box_autoadd_ffi_media_dim(
      SseDeserializer deserializer);

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_32(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer);

  @protected
  int sse_decode_u_8(SseDeserializer deserializer);

  @protected
  void sse_decode_unit(SseDeserializer deserializer);

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer);

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_ffi_delivery_event_Sse(
      RustStreamSink<FfiDeliveryEvent> self, SseSerializer serializer);

  @protected
  void sse_encode_StreamSink_ffi_feed_update_Sse(
      RustStreamSink<FfiFeedUpdate> self, SseSerializer serializer);

  @protected
  void sse_encode_String(String self, SseSerializer serializer);

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_delivery_event(
      FfiDeliveryEvent self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_feed_spec(
      FfiFeedSpec self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_feed_update(
      FfiFeedUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_focus_item(
      FfiFocusItem self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_ffi_media_dim(
      FfiMediaDim self, SseSerializer serializer);

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_delivery_event(
      FfiDeliveryEvent self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_delivery_event_kind(
      FfiDeliveryEventKind self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_creator(
      FfiFeedCreator self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_media(FfiFeedMedia self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_post(FfiFeedPost self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_spec(FfiFeedSpec self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_feed_update(FfiFeedUpdate self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_focus_item(FfiFocusItem self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_hls_playback_session(
      FfiHlsPlaybackSession self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_media_dim(FfiMediaDim self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_nostr_event_identity(
      FfiNostrEventIdentity self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_nostr_video(FfiNostrVideo self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_user_data(FfiUserData self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_video_delivery(
      FfiVideoDelivery self, SseSerializer serializer);

  @protected
  void sse_encode_ffi_video_download(
      FfiVideoDownload self, SseSerializer serializer);

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_feed_post(
      List<FfiFeedPost> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_focus_item(
      List<FfiFocusItem> self, SseSerializer serializer);

  @protected
  void sse_encode_list_ffi_video_download(
      List<FfiVideoDownload> self, SseSerializer serializer);

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer);

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_ffi_media_dim(
      FfiMediaDim? self, SseSerializer serializer);

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer);

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer);

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer);

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer);

  @protected
  void sse_encode_unit(void self, SseSerializer serializer);

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer);
}

// Section: wire_class

class RustLibWire implements BaseWire {
  factory RustLibWire.fromExternalLibrary(ExternalLibrary lib) =>
      RustLibWire(lib.ffiDynamicLibrary);

  /// Holds the symbol lookup function.
  final ffi.Pointer<T> Function<T extends ffi.NativeType>(String symbolName)
      _lookup;

  /// The symbols are looked up in [dynamicLibrary].
  RustLibWire(ffi.DynamicLibrary dynamicLibrary)
      : _lookup = dynamicLibrary.lookup;
}
