// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: unused_import, unused_element, unnecessary_import, duplicate_ignore, invalid_use_of_internal_member, annotate_overrides, non_constant_identifier_names, curly_braces_in_flow_control_structures, prefer_const_literals_to_create_immutables, unused_field

import 'api/broadcast_control.dart';
import 'api/delivery_events_stream.dart';
import 'api/delivery_types.dart';
import 'api/engine_control.dart';
import 'api/feed_control.dart';
import 'api/feed_types.dart';
import 'api/feed_updates_stream.dart';
import 'api/focus_control.dart';
import 'dart:async';
import 'dart:convert';
import 'frb_generated.dart';
import 'frb_generated.io.dart'
    if (dart.library.js_interop) 'frb_generated.web.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'video/ffi_models.dart';
import 'video/native_gateway.dart';

/// Main entrypoint of the Rust API
class RustLib extends BaseEntrypoint<RustLibApi, RustLibApiImpl, RustLibWire> {
  @internal
  static final instance = RustLib._();

  RustLib._();

  /// Initialize flutter_rust_bridge
  static Future<void> init({
    RustLibApi? api,
    BaseHandler? handler,
    ExternalLibrary? externalLibrary,
  }) async {
    await instance.initImpl(
      api: api,
      handler: handler,
      externalLibrary: externalLibrary,
    );
  }

  /// Initialize flutter_rust_bridge in mock mode.
  /// No libraries for FFI are loaded.
  static void initMock({
    required RustLibApi api,
  }) {
    instance.initMockImpl(
      api: api,
    );
  }

  /// Dispose flutter_rust_bridge
  ///
  /// The call to this function is optional, since flutter_rust_bridge (and everything else)
  /// is automatically disposed when the app stops.
  static void dispose() => instance.disposeImpl();

  @override
  ApiImplConstructor<RustLibApiImpl, RustLibWire> get apiImplConstructor =>
      RustLibApiImpl.new;

  @override
  WireConstructor<RustLibWire> get wireConstructor =>
      RustLibWire.fromExternalLibrary;

  @override
  Future<void> executeRustInitializers() async {
    await api.crateVideoNativeGatewayInitApp();
  }

  @override
  ExternalLibraryLoaderConfig get defaultExternalLibraryLoaderConfig =>
      kDefaultExternalLibraryLoaderConfig;

  @override
  String get codegenVersion => '2.7.0';

  @override
  int get rustContentHash => 1039187493;

  static const kDefaultExternalLibraryLoaderConfig =
      ExternalLibraryLoaderConfig(
    stem: 'rust_lib_ghostr',
    ioDirectory: 'rust/target/release/',
    webPrefix: 'pkg/',
  );
}

abstract class RustLibApi extends BaseApi {
  Future<FfiHlsPlaybackSession> crateVideoNativeGatewayFfiAcquireHlsPlayback(
      {required List<String> sourceUrls});

  Future<void> crateApiBroadcastControlFfiBroadcastEvent(
      {required String signedEventJson});

  Future<void> crateApiFeedControlFfiCloseFeed({required String feedId});

  Stream<FfiDeliveryEvent> crateApiDeliveryEventsStreamFfiDeliveryEvents();

  Stream<FfiFeedUpdate> crateApiFeedUpdatesStreamFfiFeedUpdates(
      {required String feedId});

  Future<List<FfiVideoDownload>>
      crateVideoNativeGatewayFfiGetDiscoveredVideos();

  Future<bool> crateApiFeedControlFfiLoadMore(
      {required String feedId, BigInt? olderThanSecs});

  Future<String> crateApiFeedControlFfiOpenFeed({required FfiFeedSpec spec});

  Future<String> crateApiFocusControlFfiPlaybackUrl(
      {required FfiFocusItem item});

  Future<bool> crateVideoNativeGatewayFfiReleaseHlsPlayback(
      {required String sessionId});

  Future<void> crateApiEngineControlFfiSetDeliveryConfig(
      {required String dataUsage, required BigInt maxStorageBytes});

  Future<String> crateApiEngineControlFfiStartEngine(
      {required String cacheDirectory,
      required String relayUrls,
      required String dataUsage,
      required BigInt maxStorageBytes});

  Future<String> crateVideoNativeGatewayFfiStartServer(
      {required String cacheDirectory,
      required BigInt maxParallelDownloads,
      required BigInt maxStorageBytes,
      required String relayUrls});

  Future<void> crateApiFocusControlFfiUpdateFocus(
      {required String feedId,
      required List<FfiFocusItem> items,
      required int currentIndex,
      required BigInt watchMs});

  Future<void> crateVideoNativeGatewayInitApp();
}

class RustLibApiImpl extends RustLibApiImplPlatform implements RustLibApi {
  RustLibApiImpl({
    required super.handler,
    required super.wire,
    required super.generalizedFrbRustBinding,
    required super.portManager,
  });

  @override
  Future<FfiHlsPlaybackSession> crateVideoNativeGatewayFfiAcquireHlsPlayback(
      {required List<String> sourceUrls}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_list_String(sourceUrls, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 3, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_ffi_hls_playback_session,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateVideoNativeGatewayFfiAcquireHlsPlaybackConstMeta,
      argValues: [sourceUrls],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateVideoNativeGatewayFfiAcquireHlsPlaybackConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_acquire_hls_playback",
        argNames: ["sourceUrls"],
      );

  @override
  Future<void> crateApiBroadcastControlFfiBroadcastEvent(
      {required String signedEventJson}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(signedEventJson, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 4, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiBroadcastControlFfiBroadcastEventConstMeta,
      argValues: [signedEventJson],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiBroadcastControlFfiBroadcastEventConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_broadcast_event",
        argNames: ["signedEventJson"],
      );

  @override
  Future<void> crateApiFeedControlFfiCloseFeed({required String feedId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(feedId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 5, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFeedControlFfiCloseFeedConstMeta,
      argValues: [feedId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFeedControlFfiCloseFeedConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_close_feed",
        argNames: ["feedId"],
      );

  @override
  Stream<FfiDeliveryEvent> crateApiDeliveryEventsStreamFfiDeliveryEvents() {
    final sink = RustStreamSink<FfiDeliveryEvent>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_StreamSink_ffi_delivery_event_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 6, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiDeliveryEventsStreamFfiDeliveryEventsConstMeta,
      argValues: [sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiDeliveryEventsStreamFfiDeliveryEventsConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_delivery_events",
        argNames: ["sink"],
      );

  @override
  Stream<FfiFeedUpdate> crateApiFeedUpdatesStreamFfiFeedUpdates(
      {required String feedId}) {
    final sink = RustStreamSink<FfiFeedUpdate>();
    unawaited(handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(feedId, serializer);
        sse_encode_StreamSink_ffi_feed_update_Sse(sink, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 7, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFeedUpdatesStreamFfiFeedUpdatesConstMeta,
      argValues: [feedId, sink],
      apiImpl: this,
    )));
    return sink.stream;
  }

  TaskConstMeta get kCrateApiFeedUpdatesStreamFfiFeedUpdatesConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_feed_updates",
        argNames: ["feedId", "sink"],
      );

  @override
  Future<List<FfiVideoDownload>>
      crateVideoNativeGatewayFfiGetDiscoveredVideos() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 8, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_list_ffi_video_download,
        decodeErrorData: null,
      ),
      constMeta: kCrateVideoNativeGatewayFfiGetDiscoveredVideosConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateVideoNativeGatewayFfiGetDiscoveredVideosConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_get_discovered_videos",
        argNames: [],
      );

  @override
  Future<bool> crateApiFeedControlFfiLoadMore(
      {required String feedId, BigInt? olderThanSecs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(feedId, serializer);
        sse_encode_opt_box_autoadd_u_64(olderThanSecs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 9, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFeedControlFfiLoadMoreConstMeta,
      argValues: [feedId, olderThanSecs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFeedControlFfiLoadMoreConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_load_more",
        argNames: ["feedId", "olderThanSecs"],
      );

  @override
  Future<String> crateApiFeedControlFfiOpenFeed({required FfiFeedSpec spec}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_ffi_feed_spec(spec, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 10, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFeedControlFfiOpenFeedConstMeta,
      argValues: [spec],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFeedControlFfiOpenFeedConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_open_feed",
        argNames: ["spec"],
      );

  @override
  Future<String> crateApiFocusControlFfiPlaybackUrl(
      {required FfiFocusItem item}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_box_autoadd_ffi_focus_item(item, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 11, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFocusControlFfiPlaybackUrlConstMeta,
      argValues: [item],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFocusControlFfiPlaybackUrlConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_playback_url",
        argNames: ["item"],
      );

  @override
  Future<bool> crateVideoNativeGatewayFfiReleaseHlsPlayback(
      {required String sessionId}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(sessionId, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 12, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_bool,
        decodeErrorData: null,
      ),
      constMeta: kCrateVideoNativeGatewayFfiReleaseHlsPlaybackConstMeta,
      argValues: [sessionId],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateVideoNativeGatewayFfiReleaseHlsPlaybackConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_release_hls_playback",
        argNames: ["sessionId"],
      );

  @override
  Future<void> crateApiEngineControlFfiSetDeliveryConfig(
      {required String dataUsage, required BigInt maxStorageBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(dataUsage, serializer);
        sse_encode_u_64(maxStorageBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 13, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEngineControlFfiSetDeliveryConfigConstMeta,
      argValues: [dataUsage, maxStorageBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineControlFfiSetDeliveryConfigConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_set_delivery_config",
        argNames: ["dataUsage", "maxStorageBytes"],
      );

  @override
  Future<String> crateApiEngineControlFfiStartEngine(
      {required String cacheDirectory,
      required String relayUrls,
      required String dataUsage,
      required BigInt maxStorageBytes}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cacheDirectory, serializer);
        sse_encode_String(relayUrls, serializer);
        sse_encode_String(dataUsage, serializer);
        sse_encode_u_64(maxStorageBytes, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 14, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiEngineControlFfiStartEngineConstMeta,
      argValues: [cacheDirectory, relayUrls, dataUsage, maxStorageBytes],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiEngineControlFfiStartEngineConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_start_engine",
        argNames: [
          "cacheDirectory",
          "relayUrls",
          "dataUsage",
          "maxStorageBytes"
        ],
      );

  @override
  Future<String> crateVideoNativeGatewayFfiStartServer(
      {required String cacheDirectory,
      required BigInt maxParallelDownloads,
      required BigInt maxStorageBytes,
      required String relayUrls}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(cacheDirectory, serializer);
        sse_encode_usize(maxParallelDownloads, serializer);
        sse_encode_u_64(maxStorageBytes, serializer);
        sse_encode_String(relayUrls, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 15, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_String,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateVideoNativeGatewayFfiStartServerConstMeta,
      argValues: [
        cacheDirectory,
        maxParallelDownloads,
        maxStorageBytes,
        relayUrls
      ],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateVideoNativeGatewayFfiStartServerConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_start_server",
        argNames: [
          "cacheDirectory",
          "maxParallelDownloads",
          "maxStorageBytes",
          "relayUrls"
        ],
      );

  @override
  Future<void> crateApiFocusControlFfiUpdateFocus(
      {required String feedId,
      required List<FfiFocusItem> items,
      required int currentIndex,
      required BigInt watchMs}) {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        sse_encode_String(feedId, serializer);
        sse_encode_list_ffi_focus_item(items, serializer);
        sse_encode_u_32(currentIndex, serializer);
        sse_encode_u_64(watchMs, serializer);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 16, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: sse_decode_AnyhowException,
      ),
      constMeta: kCrateApiFocusControlFfiUpdateFocusConstMeta,
      argValues: [feedId, items, currentIndex, watchMs],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateApiFocusControlFfiUpdateFocusConstMeta =>
      const TaskConstMeta(
        debugName: "ffi_update_focus",
        argNames: ["feedId", "items", "currentIndex", "watchMs"],
      );

  @override
  Future<void> crateVideoNativeGatewayInitApp() {
    return handler.executeNormal(NormalTask(
      callFfi: (port_) {
        final serializer = SseSerializer(generalizedFrbRustBinding);
        pdeCallFfi(generalizedFrbRustBinding, serializer,
            funcId: 17, port: port_);
      },
      codec: SseCodec(
        decodeSuccessData: sse_decode_unit,
        decodeErrorData: null,
      ),
      constMeta: kCrateVideoNativeGatewayInitAppConstMeta,
      argValues: [],
      apiImpl: this,
    ));
  }

  TaskConstMeta get kCrateVideoNativeGatewayInitAppConstMeta =>
      const TaskConstMeta(
        debugName: "init_app",
        argNames: [],
      );

  @protected
  AnyhowException dco_decode_AnyhowException(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return AnyhowException(raw as String);
  }

  @protected
  RustStreamSink<FfiDeliveryEvent> dco_decode_StreamSink_ffi_delivery_event_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  RustStreamSink<FfiFeedUpdate> dco_decode_StreamSink_ffi_feed_update_Sse(
      dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  String dco_decode_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as String;
  }

  @protected
  EventOut dco_decode_TraitDef_EventOut(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  FeedOut dco_decode_TraitDef_FeedOut(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    throw UnimplementedError();
  }

  @protected
  bool dco_decode_bool(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as bool;
  }

  @protected
  FfiDeliveryEvent dco_decode_box_autoadd_ffi_delivery_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_delivery_event(raw);
  }

  @protected
  FfiFeedSpec dco_decode_box_autoadd_ffi_feed_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_feed_spec(raw);
  }

  @protected
  FfiFeedUpdate dco_decode_box_autoadd_ffi_feed_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_feed_update(raw);
  }

  @protected
  FfiFocusItem dco_decode_box_autoadd_ffi_focus_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_focus_item(raw);
  }

  @protected
  FfiMediaDim dco_decode_box_autoadd_ffi_media_dim(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_ffi_media_dim(raw);
  }

  @protected
  BigInt dco_decode_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dco_decode_u_64(raw);
  }

  @protected
  FfiDeliveryEvent dco_decode_ffi_delivery_event(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FfiDeliveryEvent(
      postId: dco_decode_String(arr[0]),
      kind: dco_decode_ffi_delivery_event_kind(arr[1]),
      startable: dco_decode_bool(arr[2]),
      bytesPresent: dco_decode_u_64(arr[3]),
      totalBytes: dco_decode_opt_box_autoadd_u_64(arr[4]),
      detail: dco_decode_opt_String(arr[5]),
    );
  }

  @protected
  FfiDeliveryEventKind dco_decode_ffi_delivery_event_kind(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiDeliveryEventKind.values[raw as int];
  }

  @protected
  FfiFeedCreator dco_decode_ffi_feed_creator(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiFeedCreator(
      pubkey: dco_decode_String(arr[0]),
      displayName: dco_decode_String(arr[1]),
      handle: dco_decode_String(arr[2]),
      avatarUrl: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FfiFeedMedia dco_decode_ffi_feed_media(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 8)
      throw Exception('unexpected arr length: expect 8 but see ${arr.length}');
    return FfiFeedMedia(
      urls: dco_decode_list_String(arr[0]),
      delivery: dco_decode_String(arr[1]),
      sha256: dco_decode_opt_String(arr[2]),
      sizeBytes: dco_decode_opt_box_autoadd_u_64(arr[3]),
      durationMs: dco_decode_opt_box_autoadd_u_64(arr[4]),
      dim: dco_decode_opt_box_autoadd_ffi_media_dim(arr[5]),
      blurhash: dco_decode_opt_String(arr[6]),
      thumbUrl: dco_decode_opt_String(arr[7]),
    );
  }

  @protected
  FfiFeedPost dco_decode_ffi_feed_post(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 9)
      throw Exception('unexpected arr length: expect 9 but see ${arr.length}');
    return FfiFeedPost(
      postId: dco_decode_String(arr[0]),
      eventId: dco_decode_String(arr[1]),
      eventKind: dco_decode_u_16(arr[2]),
      identifier: dco_decode_opt_String(arr[3]),
      createdAt: dco_decode_u_64(arr[4]),
      caption: dco_decode_String(arr[5]),
      hashtags: dco_decode_list_String(arr[6]),
      creator: dco_decode_ffi_feed_creator(arr[7]),
      media: dco_decode_ffi_feed_media(arr[8]),
    );
  }

  @protected
  FfiFeedSpec dco_decode_ffi_feed_spec(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiFeedSpec(
      kind: dco_decode_String(arr[0]),
      value: dco_decode_opt_String(arr[1]),
      creators: dco_decode_list_String(arr[2]),
      viewerPubkey: dco_decode_opt_String(arr[3]),
    );
  }

  @protected
  FfiFeedStage dco_decode_ffi_feed_stage(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiFeedStage.values[raw as int];
  }

  @protected
  FfiFeedUpdate dco_decode_ffi_feed_update(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 4)
      throw Exception('unexpected arr length: expect 4 but see ${arr.length}');
    return FfiFeedUpdate(
      feedId: dco_decode_String(arr[0]),
      revision: dco_decode_u_64(arr[1]),
      stage: dco_decode_ffi_feed_stage(arr[2]),
      posts: dco_decode_list_ffi_feed_post(arr[3]),
    );
  }

  @protected
  FfiFocusItem dco_decode_ffi_focus_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FfiFocusItem(
      postId: dco_decode_String(arr[0]),
      urls: dco_decode_list_String(arr[1]),
      delivery: dco_decode_String(arr[2]),
      sha256: dco_decode_opt_String(arr[3]),
      sizeBytes: dco_decode_opt_box_autoadd_u_64(arr[4]),
      durationMs: dco_decode_opt_box_autoadd_u_64(arr[5]),
    );
  }

  @protected
  FfiHlsPlaybackSession dco_decode_ffi_hls_playback_session(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiHlsPlaybackSession(
      sessionId: dco_decode_String(arr[0]),
      playbackUrl: dco_decode_String(arr[1]),
    );
  }

  @protected
  FfiMediaDim dco_decode_ffi_media_dim(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 2)
      throw Exception('unexpected arr length: expect 2 but see ${arr.length}');
    return FfiMediaDim(
      width: dco_decode_u_32(arr[0]),
      height: dco_decode_u_32(arr[1]),
    );
  }

  @protected
  FfiNostrEventIdentity dco_decode_ffi_nostr_event_identity(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 7)
      throw Exception('unexpected arr length: expect 7 but see ${arr.length}');
    return FfiNostrEventIdentity(
      eventId: dco_decode_String(arr[0]),
      authorPublicKeyHex: dco_decode_String(arr[1]),
      kind: dco_decode_u_64(arr[2]),
      identifier: dco_decode_opt_String(arr[3]),
      createdAt: dco_decode_u_64(arr[4]),
      content: dco_decode_String(arr[5]),
      hashtags: dco_decode_list_String(arr[6]),
    );
  }

  @protected
  FfiNostrVideo dco_decode_ffi_nostr_video(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 10)
      throw Exception('unexpected arr length: expect 10 but see ${arr.length}');
    return FfiNostrVideo(
      id: dco_decode_String(arr[0]),
      expectedDigest: dco_decode_opt_String(arr[1]),
      fallbackUrls: dco_decode_list_String(arr[2]),
      user: dco_decode_ffi_user_data(arr[3]),
      title: dco_decode_String(arr[4]),
      songName: dco_decode_String(arr[5]),
      likes: dco_decode_String(arr[6]),
      comments: dco_decode_String(arr[7]),
      url: dco_decode_String(arr[8]),
      delivery: dco_decode_ffi_video_delivery(arr[9]),
    );
  }

  @protected
  FfiUserData dco_decode_ffi_user_data(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 3)
      throw Exception('unexpected arr length: expect 3 but see ${arr.length}');
    return FfiUserData(
      npub: dco_decode_opt_String(arr[0]),
      name: dco_decode_opt_String(arr[1]),
      profilePicture: dco_decode_opt_String(arr[2]),
    );
  }

  @protected
  FfiVideoDelivery dco_decode_ffi_video_delivery(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return FfiVideoDelivery.values[raw as int];
  }

  @protected
  FfiVideoDownload dco_decode_ffi_video_download(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    final arr = raw as List<dynamic>;
    if (arr.length != 6)
      throw Exception('unexpected arr length: expect 6 but see ${arr.length}');
    return FfiVideoDownload(
      id: dco_decode_String(arr[0]),
      url: dco_decode_String(arr[1]),
      title: dco_decode_opt_String(arr[2]),
      localPath: dco_decode_opt_String(arr[3]),
      event: dco_decode_ffi_nostr_event_identity(arr[4]),
      nostr: dco_decode_ffi_nostr_video(arr[5]),
    );
  }

  @protected
  int dco_decode_i_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  List<String> dco_decode_list_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_String).toList();
  }

  @protected
  List<FfiFeedPost> dco_decode_list_ffi_feed_post(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_feed_post).toList();
  }

  @protected
  List<FfiFocusItem> dco_decode_list_ffi_focus_item(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_focus_item).toList();
  }

  @protected
  List<FfiVideoDownload> dco_decode_list_ffi_video_download(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return (raw as List<dynamic>).map(dco_decode_ffi_video_download).toList();
  }

  @protected
  Uint8List dco_decode_list_prim_u_8_strict(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as Uint8List;
  }

  @protected
  String? dco_decode_opt_String(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_String(raw);
  }

  @protected
  FfiMediaDim? dco_decode_opt_box_autoadd_ffi_media_dim(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_ffi_media_dim(raw);
  }

  @protected
  BigInt? dco_decode_opt_box_autoadd_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw == null ? null : dco_decode_box_autoadd_u_64(raw);
  }

  @protected
  int dco_decode_u_16(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  int dco_decode_u_32(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  BigInt dco_decode_u_64(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  int dco_decode_u_8(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return raw as int;
  }

  @protected
  void dco_decode_unit(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return;
  }

  @protected
  BigInt dco_decode_usize(dynamic raw) {
    // Codec=Dco (DartCObject based), see doc to use other codecs
    return dcoDecodeU64(raw);
  }

  @protected
  AnyhowException sse_decode_AnyhowException(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_String(deserializer);
    return AnyhowException(inner);
  }

  @protected
  RustStreamSink<FfiDeliveryEvent> sse_decode_StreamSink_ffi_delivery_event_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  RustStreamSink<FfiFeedUpdate> sse_decode_StreamSink_ffi_feed_update_Sse(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    throw UnimplementedError('Unreachable ()');
  }

  @protected
  String sse_decode_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_list_prim_u_8_strict(deserializer);
    return utf8.decoder.convert(inner);
  }

  @protected
  bool sse_decode_bool(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8() != 0;
  }

  @protected
  FfiDeliveryEvent sse_decode_box_autoadd_ffi_delivery_event(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_delivery_event(deserializer));
  }

  @protected
  FfiFeedSpec sse_decode_box_autoadd_ffi_feed_spec(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_feed_spec(deserializer));
  }

  @protected
  FfiFeedUpdate sse_decode_box_autoadd_ffi_feed_update(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_feed_update(deserializer));
  }

  @protected
  FfiFocusItem sse_decode_box_autoadd_ffi_focus_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_focus_item(deserializer));
  }

  @protected
  FfiMediaDim sse_decode_box_autoadd_ffi_media_dim(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_ffi_media_dim(deserializer));
  }

  @protected
  BigInt sse_decode_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return (sse_decode_u_64(deserializer));
  }

  @protected
  FfiDeliveryEvent sse_decode_ffi_delivery_event(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_postId = sse_decode_String(deserializer);
    var var_kind = sse_decode_ffi_delivery_event_kind(deserializer);
    var var_startable = sse_decode_bool(deserializer);
    var var_bytesPresent = sse_decode_u_64(deserializer);
    var var_totalBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_detail = sse_decode_opt_String(deserializer);
    return FfiDeliveryEvent(
        postId: var_postId,
        kind: var_kind,
        startable: var_startable,
        bytesPresent: var_bytesPresent,
        totalBytes: var_totalBytes,
        detail: var_detail);
  }

  @protected
  FfiDeliveryEventKind sse_decode_ffi_delivery_event_kind(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiDeliveryEventKind.values[inner];
  }

  @protected
  FfiFeedCreator sse_decode_ffi_feed_creator(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_pubkey = sse_decode_String(deserializer);
    var var_displayName = sse_decode_String(deserializer);
    var var_handle = sse_decode_String(deserializer);
    var var_avatarUrl = sse_decode_opt_String(deserializer);
    return FfiFeedCreator(
        pubkey: var_pubkey,
        displayName: var_displayName,
        handle: var_handle,
        avatarUrl: var_avatarUrl);
  }

  @protected
  FfiFeedMedia sse_decode_ffi_feed_media(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_urls = sse_decode_list_String(deserializer);
    var var_delivery = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_opt_String(deserializer);
    var var_sizeBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_dim = sse_decode_opt_box_autoadd_ffi_media_dim(deserializer);
    var var_blurhash = sse_decode_opt_String(deserializer);
    var var_thumbUrl = sse_decode_opt_String(deserializer);
    return FfiFeedMedia(
        urls: var_urls,
        delivery: var_delivery,
        sha256: var_sha256,
        sizeBytes: var_sizeBytes,
        durationMs: var_durationMs,
        dim: var_dim,
        blurhash: var_blurhash,
        thumbUrl: var_thumbUrl);
  }

  @protected
  FfiFeedPost sse_decode_ffi_feed_post(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_postId = sse_decode_String(deserializer);
    var var_eventId = sse_decode_String(deserializer);
    var var_eventKind = sse_decode_u_16(deserializer);
    var var_identifier = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_caption = sse_decode_String(deserializer);
    var var_hashtags = sse_decode_list_String(deserializer);
    var var_creator = sse_decode_ffi_feed_creator(deserializer);
    var var_media = sse_decode_ffi_feed_media(deserializer);
    return FfiFeedPost(
        postId: var_postId,
        eventId: var_eventId,
        eventKind: var_eventKind,
        identifier: var_identifier,
        createdAt: var_createdAt,
        caption: var_caption,
        hashtags: var_hashtags,
        creator: var_creator,
        media: var_media);
  }

  @protected
  FfiFeedSpec sse_decode_ffi_feed_spec(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_kind = sse_decode_String(deserializer);
    var var_value = sse_decode_opt_String(deserializer);
    var var_creators = sse_decode_list_String(deserializer);
    var var_viewerPubkey = sse_decode_opt_String(deserializer);
    return FfiFeedSpec(
        kind: var_kind,
        value: var_value,
        creators: var_creators,
        viewerPubkey: var_viewerPubkey);
  }

  @protected
  FfiFeedStage sse_decode_ffi_feed_stage(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiFeedStage.values[inner];
  }

  @protected
  FfiFeedUpdate sse_decode_ffi_feed_update(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_feedId = sse_decode_String(deserializer);
    var var_revision = sse_decode_u_64(deserializer);
    var var_stage = sse_decode_ffi_feed_stage(deserializer);
    var var_posts = sse_decode_list_ffi_feed_post(deserializer);
    return FfiFeedUpdate(
        feedId: var_feedId,
        revision: var_revision,
        stage: var_stage,
        posts: var_posts);
  }

  @protected
  FfiFocusItem sse_decode_ffi_focus_item(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_postId = sse_decode_String(deserializer);
    var var_urls = sse_decode_list_String(deserializer);
    var var_delivery = sse_decode_String(deserializer);
    var var_sha256 = sse_decode_opt_String(deserializer);
    var var_sizeBytes = sse_decode_opt_box_autoadd_u_64(deserializer);
    var var_durationMs = sse_decode_opt_box_autoadd_u_64(deserializer);
    return FfiFocusItem(
        postId: var_postId,
        urls: var_urls,
        delivery: var_delivery,
        sha256: var_sha256,
        sizeBytes: var_sizeBytes,
        durationMs: var_durationMs);
  }

  @protected
  FfiHlsPlaybackSession sse_decode_ffi_hls_playback_session(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_sessionId = sse_decode_String(deserializer);
    var var_playbackUrl = sse_decode_String(deserializer);
    return FfiHlsPlaybackSession(
        sessionId: var_sessionId, playbackUrl: var_playbackUrl);
  }

  @protected
  FfiMediaDim sse_decode_ffi_media_dim(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_width = sse_decode_u_32(deserializer);
    var var_height = sse_decode_u_32(deserializer);
    return FfiMediaDim(width: var_width, height: var_height);
  }

  @protected
  FfiNostrEventIdentity sse_decode_ffi_nostr_event_identity(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_eventId = sse_decode_String(deserializer);
    var var_authorPublicKeyHex = sse_decode_String(deserializer);
    var var_kind = sse_decode_u_64(deserializer);
    var var_identifier = sse_decode_opt_String(deserializer);
    var var_createdAt = sse_decode_u_64(deserializer);
    var var_content = sse_decode_String(deserializer);
    var var_hashtags = sse_decode_list_String(deserializer);
    return FfiNostrEventIdentity(
        eventId: var_eventId,
        authorPublicKeyHex: var_authorPublicKeyHex,
        kind: var_kind,
        identifier: var_identifier,
        createdAt: var_createdAt,
        content: var_content,
        hashtags: var_hashtags);
  }

  @protected
  FfiNostrVideo sse_decode_ffi_nostr_video(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_expectedDigest = sse_decode_opt_String(deserializer);
    var var_fallbackUrls = sse_decode_list_String(deserializer);
    var var_user = sse_decode_ffi_user_data(deserializer);
    var var_title = sse_decode_String(deserializer);
    var var_songName = sse_decode_String(deserializer);
    var var_likes = sse_decode_String(deserializer);
    var var_comments = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_delivery = sse_decode_ffi_video_delivery(deserializer);
    return FfiNostrVideo(
        id: var_id,
        expectedDigest: var_expectedDigest,
        fallbackUrls: var_fallbackUrls,
        user: var_user,
        title: var_title,
        songName: var_songName,
        likes: var_likes,
        comments: var_comments,
        url: var_url,
        delivery: var_delivery);
  }

  @protected
  FfiUserData sse_decode_ffi_user_data(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_npub = sse_decode_opt_String(deserializer);
    var var_name = sse_decode_opt_String(deserializer);
    var var_profilePicture = sse_decode_opt_String(deserializer);
    return FfiUserData(
        npub: var_npub, name: var_name, profilePicture: var_profilePicture);
  }

  @protected
  FfiVideoDelivery sse_decode_ffi_video_delivery(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var inner = sse_decode_i_32(deserializer);
    return FfiVideoDelivery.values[inner];
  }

  @protected
  FfiVideoDownload sse_decode_ffi_video_download(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var var_id = sse_decode_String(deserializer);
    var var_url = sse_decode_String(deserializer);
    var var_title = sse_decode_opt_String(deserializer);
    var var_localPath = sse_decode_opt_String(deserializer);
    var var_event = sse_decode_ffi_nostr_event_identity(deserializer);
    var var_nostr = sse_decode_ffi_nostr_video(deserializer);
    return FfiVideoDownload(
        id: var_id,
        url: var_url,
        title: var_title,
        localPath: var_localPath,
        event: var_event,
        nostr: var_nostr);
  }

  @protected
  int sse_decode_i_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getInt32();
  }

  @protected
  List<String> sse_decode_list_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <String>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_String(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiFeedPost> sse_decode_list_ffi_feed_post(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiFeedPost>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_feed_post(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiFocusItem> sse_decode_list_ffi_focus_item(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiFocusItem>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_focus_item(deserializer));
    }
    return ans_;
  }

  @protected
  List<FfiVideoDownload> sse_decode_list_ffi_video_download(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    var len_ = sse_decode_i_32(deserializer);
    var ans_ = <FfiVideoDownload>[];
    for (var idx_ = 0; idx_ < len_; ++idx_) {
      ans_.add(sse_decode_ffi_video_download(deserializer));
    }
    return ans_;
  }

  @protected
  Uint8List sse_decode_list_prim_u_8_strict(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    var len_ = sse_decode_i_32(deserializer);
    return deserializer.buffer.getUint8List(len_);
  }

  @protected
  String? sse_decode_opt_String(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_String(deserializer));
    } else {
      return null;
    }
  }

  @protected
  FfiMediaDim? sse_decode_opt_box_autoadd_ffi_media_dim(
      SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_ffi_media_dim(deserializer));
    } else {
      return null;
    }
  }

  @protected
  BigInt? sse_decode_opt_box_autoadd_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    if (sse_decode_bool(deserializer)) {
      return (sse_decode_box_autoadd_u_64(deserializer));
    } else {
      return null;
    }
  }

  @protected
  int sse_decode_u_16(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint16();
  }

  @protected
  int sse_decode_u_32(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint32();
  }

  @protected
  BigInt sse_decode_u_64(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  int sse_decode_u_8(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getUint8();
  }

  @protected
  void sse_decode_unit(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  BigInt sse_decode_usize(SseDeserializer deserializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    return deserializer.buffer.getBigUint64();
  }

  @protected
  void sse_encode_AnyhowException(
      AnyhowException self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.message, serializer);
  }

  @protected
  void sse_encode_StreamSink_ffi_delivery_event_Sse(
      RustStreamSink<FfiDeliveryEvent> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_delivery_event,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_StreamSink_ffi_feed_update_Sse(
      RustStreamSink<FfiFeedUpdate> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(
        self.setupAndSerialize(
            codec: SseCodec(
          decodeSuccessData: sse_decode_ffi_feed_update,
          decodeErrorData: sse_decode_AnyhowException,
        )),
        serializer);
  }

  @protected
  void sse_encode_String(String self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_prim_u_8_strict(utf8.encoder.convert(self), serializer);
  }

  @protected
  void sse_encode_bool(bool self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self ? 1 : 0);
  }

  @protected
  void sse_encode_box_autoadd_ffi_delivery_event(
      FfiDeliveryEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_delivery_event(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_feed_spec(
      FfiFeedSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_feed_spec(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_feed_update(
      FfiFeedUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_feed_update(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_focus_item(
      FfiFocusItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_focus_item(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_ffi_media_dim(
      FfiMediaDim self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_ffi_media_dim(self, serializer);
  }

  @protected
  void sse_encode_box_autoadd_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_64(self, serializer);
  }

  @protected
  void sse_encode_ffi_delivery_event(
      FfiDeliveryEvent self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.postId, serializer);
    sse_encode_ffi_delivery_event_kind(self.kind, serializer);
    sse_encode_bool(self.startable, serializer);
    sse_encode_u_64(self.bytesPresent, serializer);
    sse_encode_opt_box_autoadd_u_64(self.totalBytes, serializer);
    sse_encode_opt_String(self.detail, serializer);
  }

  @protected
  void sse_encode_ffi_delivery_event_kind(
      FfiDeliveryEventKind self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_feed_creator(
      FfiFeedCreator self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.pubkey, serializer);
    sse_encode_String(self.displayName, serializer);
    sse_encode_String(self.handle, serializer);
    sse_encode_opt_String(self.avatarUrl, serializer);
  }

  @protected
  void sse_encode_ffi_feed_media(FfiFeedMedia self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_list_String(self.urls, serializer);
    sse_encode_String(self.delivery, serializer);
    sse_encode_opt_String(self.sha256, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sizeBytes, serializer);
    sse_encode_opt_box_autoadd_u_64(self.durationMs, serializer);
    sse_encode_opt_box_autoadd_ffi_media_dim(self.dim, serializer);
    sse_encode_opt_String(self.blurhash, serializer);
    sse_encode_opt_String(self.thumbUrl, serializer);
  }

  @protected
  void sse_encode_ffi_feed_post(FfiFeedPost self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.postId, serializer);
    sse_encode_String(self.eventId, serializer);
    sse_encode_u_16(self.eventKind, serializer);
    sse_encode_opt_String(self.identifier, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_String(self.caption, serializer);
    sse_encode_list_String(self.hashtags, serializer);
    sse_encode_ffi_feed_creator(self.creator, serializer);
    sse_encode_ffi_feed_media(self.media, serializer);
  }

  @protected
  void sse_encode_ffi_feed_spec(FfiFeedSpec self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.kind, serializer);
    sse_encode_opt_String(self.value, serializer);
    sse_encode_list_String(self.creators, serializer);
    sse_encode_opt_String(self.viewerPubkey, serializer);
  }

  @protected
  void sse_encode_ffi_feed_stage(FfiFeedStage self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_feed_update(
      FfiFeedUpdate self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.feedId, serializer);
    sse_encode_u_64(self.revision, serializer);
    sse_encode_ffi_feed_stage(self.stage, serializer);
    sse_encode_list_ffi_feed_post(self.posts, serializer);
  }

  @protected
  void sse_encode_ffi_focus_item(FfiFocusItem self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.postId, serializer);
    sse_encode_list_String(self.urls, serializer);
    sse_encode_String(self.delivery, serializer);
    sse_encode_opt_String(self.sha256, serializer);
    sse_encode_opt_box_autoadd_u_64(self.sizeBytes, serializer);
    sse_encode_opt_box_autoadd_u_64(self.durationMs, serializer);
  }

  @protected
  void sse_encode_ffi_hls_playback_session(
      FfiHlsPlaybackSession self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.sessionId, serializer);
    sse_encode_String(self.playbackUrl, serializer);
  }

  @protected
  void sse_encode_ffi_media_dim(FfiMediaDim self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_u_32(self.width, serializer);
    sse_encode_u_32(self.height, serializer);
  }

  @protected
  void sse_encode_ffi_nostr_event_identity(
      FfiNostrEventIdentity self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.eventId, serializer);
    sse_encode_String(self.authorPublicKeyHex, serializer);
    sse_encode_u_64(self.kind, serializer);
    sse_encode_opt_String(self.identifier, serializer);
    sse_encode_u_64(self.createdAt, serializer);
    sse_encode_String(self.content, serializer);
    sse_encode_list_String(self.hashtags, serializer);
  }

  @protected
  void sse_encode_ffi_nostr_video(
      FfiNostrVideo self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_opt_String(self.expectedDigest, serializer);
    sse_encode_list_String(self.fallbackUrls, serializer);
    sse_encode_ffi_user_data(self.user, serializer);
    sse_encode_String(self.title, serializer);
    sse_encode_String(self.songName, serializer);
    sse_encode_String(self.likes, serializer);
    sse_encode_String(self.comments, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_ffi_video_delivery(self.delivery, serializer);
  }

  @protected
  void sse_encode_ffi_user_data(FfiUserData self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_opt_String(self.npub, serializer);
    sse_encode_opt_String(self.name, serializer);
    sse_encode_opt_String(self.profilePicture, serializer);
  }

  @protected
  void sse_encode_ffi_video_delivery(
      FfiVideoDelivery self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.index, serializer);
  }

  @protected
  void sse_encode_ffi_video_download(
      FfiVideoDownload self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_String(self.id, serializer);
    sse_encode_String(self.url, serializer);
    sse_encode_opt_String(self.title, serializer);
    sse_encode_opt_String(self.localPath, serializer);
    sse_encode_ffi_nostr_event_identity(self.event, serializer);
    sse_encode_ffi_nostr_video(self.nostr, serializer);
  }

  @protected
  void sse_encode_i_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putInt32(self);
  }

  @protected
  void sse_encode_list_String(List<String> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_String(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_feed_post(
      List<FfiFeedPost> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_feed_post(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_focus_item(
      List<FfiFocusItem> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_focus_item(item, serializer);
    }
  }

  @protected
  void sse_encode_list_ffi_video_download(
      List<FfiVideoDownload> self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    for (final item in self) {
      sse_encode_ffi_video_download(item, serializer);
    }
  }

  @protected
  void sse_encode_list_prim_u_8_strict(
      Uint8List self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    sse_encode_i_32(self.length, serializer);
    serializer.buffer.putUint8List(self);
  }

  @protected
  void sse_encode_opt_String(String? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_String(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_ffi_media_dim(
      FfiMediaDim? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_ffi_media_dim(self, serializer);
    }
  }

  @protected
  void sse_encode_opt_box_autoadd_u_64(BigInt? self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs

    sse_encode_bool(self != null, serializer);
    if (self != null) {
      sse_encode_box_autoadd_u_64(self, serializer);
    }
  }

  @protected
  void sse_encode_u_16(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint16(self);
  }

  @protected
  void sse_encode_u_32(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint32(self);
  }

  @protected
  void sse_encode_u_64(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }

  @protected
  void sse_encode_u_8(int self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putUint8(self);
  }

  @protected
  void sse_encode_unit(void self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
  }

  @protected
  void sse_encode_usize(BigInt self, SseSerializer serializer) {
    // Codec=Sse (Serialization based), see doc to use other codecs
    serializer.buffer.putBigUint64(self);
  }
}
