#!/bin/sh
set -eu

root=$(CDPATH= cd -- "$(dirname "$0")/../.." && pwd)
makefile="$root/Makefile"
runner="$root/tool/run_video_player_contract_android.sh"
root_cargo="$root/rust/Cargo.toml"
gateway_lib="$root/rust/crates/gateway/src/lib.rs"
gateway_runtime="$root/rust/crates/gateway/src/runtime.rs"
gateway_media="$root/rust/crates/gateway/src/runtime/media.rs"
device_client="$root/rust/crates/gateway/src/device_integration.rs"

grep -Fq 'video-progressive-suite:' "$makefile"
grep -Fq 'video-progressive-android:' "$makefile"
grep -Fq 'VIDEO_PROGRESSIVE_FLUTTER_TESTS :=' "$makefile"
grep -Fq 'integration_test/progressive_delivery_video_test.dart' "$makefile"
grep -Fq 'integration_test/warp_feed_playback_video_test.dart' "$makefile"
grep -Fq 'integration_test/warp_feed_visible_motion_video_test.dart' "$makefile"
grep -Fq 'feed_backfill_stationary_cursor_test.dart' "$makefile"
grep -Fq 'feed_focus_sink_contract_test.dart' "$makefile"
grep -Fq 'progressive_device_resources_test.dart' "$makefile"
grep -Fq 'device_video_frame_evidence_test.dart' "$makefile"
grep -Fq 'progressive_device_fixture_parity_test.dart' "$makefile"
grep -Fq 'warp_feed_player_stage_history_test.dart' "$makefile"
grep -Fq 'ffi_playback_telemetry_cross_port_generation_test.dart' "$makefile"
grep -Fq 'ffi_playback_telemetry_deactivation_collapse_test.dart' "$makefile"
grep -Fq 'ffi_playback_telemetry_late_deactivation_test.dart' "$makefile"
grep -Fq 'ffi_playback_telemetry_terminal_synthesis_test.dart' "$makefile"
grep -Fq 'ffi_video_gateway_device_integration_scope_test.dart' "$makefile"
grep -Fq 'feed_focus_lease_contract_test.dart' "$makefile"
grep -Fq 'cargo test -p ghostr-engine --all-features' "$makefile"
grep -Fq 'cargo test -p ghostr-delivery --all-features' "$makefile"
grep -Fq 'delivery_next_reserve_evidence_test' "$makefile"
grep -Fq 'cargo test -p ghostr-gateway --all-features' "$makefile"
grep -Fq 'run_video_player_contract_android.sh' "$makefile"
grep -Fq 'device-integration' "$root/rust/cargokit.yaml"
grep -Fq 'device-integration = ["ghostr-gateway/device-integration"]' "$root_cargo"
grep -Fq 'all(feature = "device-integration", debug_assertions)' "$gateway_lib"
grep -Fq 'device_integration_origin: Option<String>' "$gateway_runtime"
grep -Fq 'all(feature = "device-integration", debug_assertions)' "$gateway_media"
grep -Fq 'DeviceIntegrationMediaHttpClient::new(origin)' "$gateway_media"
grep -Fq 'MEDIA_CONNECT_TIMEOUT' "$device_client"
grep -Fq 'MEDIA_REQUEST_TIMEOUT' "$device_client"
grep -Fq 'make android-agent-avd-create' "$runner"
grep -Fq 'make android-agent-avd-run' "$runner"
