// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

class FfiNostrEventIdentity {
  final String eventId;
  final String authorPublicKeyHex;
  final BigInt kind;
  final String? identifier;
  final BigInt createdAt;
  final String content;

  const FfiNostrEventIdentity({
    required this.eventId,
    required this.authorPublicKeyHex,
    required this.kind,
    this.identifier,
    required this.createdAt,
    required this.content,
  });

  @override
  int get hashCode =>
      eventId.hashCode ^
      authorPublicKeyHex.hashCode ^
      kind.hashCode ^
      identifier.hashCode ^
      createdAt.hashCode ^
      content.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiNostrEventIdentity &&
          runtimeType == other.runtimeType &&
          eventId == other.eventId &&
          authorPublicKeyHex == other.authorPublicKeyHex &&
          kind == other.kind &&
          identifier == other.identifier &&
          createdAt == other.createdAt &&
          content == other.content;
}

class FfiNostrVideo {
  final String id;
  final FfiUserData user;
  final String title;
  final String songName;
  final String likes;
  final String comments;
  final String url;
  final FfiVideoDelivery delivery;

  const FfiNostrVideo({
    required this.id,
    required this.user,
    required this.title,
    required this.songName,
    required this.likes,
    required this.comments,
    required this.url,
    required this.delivery,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      user.hashCode ^
      title.hashCode ^
      songName.hashCode ^
      likes.hashCode ^
      comments.hashCode ^
      url.hashCode ^
      delivery.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiNostrVideo &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          user == other.user &&
          title == other.title &&
          songName == other.songName &&
          likes == other.likes &&
          comments == other.comments &&
          url == other.url &&
          delivery == other.delivery;
}

class FfiUserData {
  final String? npub;
  final String? name;
  final String? profilePicture;

  const FfiUserData({
    this.npub,
    this.name,
    this.profilePicture,
  });

  @override
  int get hashCode => npub.hashCode ^ name.hashCode ^ profilePicture.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiUserData &&
          runtimeType == other.runtimeType &&
          npub == other.npub &&
          name == other.name &&
          profilePicture == other.profilePicture;
}

enum FfiVideoDelivery {
  progressive,
  hls,
  ;
}

class FfiVideoDownload {
  final String id;
  final String url;
  final String? title;
  final String? localPath;
  final FfiNostrEventIdentity event;
  final FfiNostrVideo nostr;

  const FfiVideoDownload({
    required this.id,
    required this.url,
    this.title,
    this.localPath,
    required this.event,
    required this.nostr,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      url.hashCode ^
      title.hashCode ^
      localPath.hashCode ^
      event.hashCode ^
      nostr.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiVideoDownload &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          url == other.url &&
          title == other.title &&
          localPath == other.localPath &&
          event == other.event &&
          nostr == other.nostr;
}
