// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ffi_models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `install_runtime`, `relay_list`

Future<String> ffiStartServer(
        {required String cacheDirectory,
        required BigInt maxParallelDownloads,
        required BigInt maxStorageBytes,
        required String relayUrls}) =>
    RustLib.instance.api.crateVideoNativeGatewayFfiStartServer(
        cacheDirectory: cacheDirectory,
        maxParallelDownloads: maxParallelDownloads,
        maxStorageBytes: maxStorageBytes,
        relayUrls: relayUrls);

Future<List<FfiVideoDownload>> ffiGetDiscoveredVideos() =>
    RustLib.instance.api.crateVideoNativeGatewayFfiGetDiscoveredVideos();
