// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'ffi_models.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Deprecated alias for `ffi_start_engine` (plan §2): same start path
/// and shared runtime, with the data-usage level left at its Balanced
/// default. Kept only until the Dart wiring moves to the new call.
Future<String> ffiStartServer(
        {required String cacheDirectory,
        required BigInt maxParallelDownloads,
        required BigInt maxStorageBytes,
        required String relayUrls}) =>
    RustLib.instance.api.crateVideoNativeGatewayFfiStartServer(
        cacheDirectory: cacheDirectory,
        maxParallelDownloads: maxParallelDownloads,
        maxStorageBytes: maxStorageBytes,
        relayUrls: relayUrls);

Future<List<FfiVideoDownload>> ffiGetDiscoveredVideos() =>
    RustLib.instance.api.crateVideoNativeGatewayFfiGetDiscoveredVideos();

Future<FfiHlsPlaybackSession> ffiAcquireHlsPlayback(
        {required List<String> sourceUrls}) =>
    RustLib.instance.api
        .crateVideoNativeGatewayFfiAcquireHlsPlayback(sourceUrls: sourceUrls);

Future<bool> ffiReleaseHlsPlayback({required String sessionId}) =>
    RustLib.instance.api
        .crateVideoNativeGatewayFfiReleaseHlsPlayback(sessionId: sessionId);
