// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `broadcast_relays`, `broadcast`, `ensure_relays`, `verified_event`

/// Validates one pre-signed event and publishes it with outbox-aware
/// relay selection: the author's declared write relays after the
/// bootstrap set, capped by the current data-usage level.
Future<void> ffiBroadcastEvent({required String signedEventJson}) =>
    RustLib.instance.api.crateApiBroadcastControlFfiBroadcastEvent(
        signedEventJson: signedEventJson);
