// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// One per-post delivery update streamed to Dart.
class FfiDeliveryEvent {
  final String postId;
  final FfiDeliveryEventKind kind;
  final bool startable;
  final BigInt bytesPresent;
  final BigInt? totalBytes;

  /// Best current completion estimate; absent when the engine cannot
  /// make a defensible estimate.
  final BigInt? etaMs;
  final String? detail;

  const FfiDeliveryEvent({
    required this.postId,
    required this.kind,
    required this.startable,
    required this.bytesPresent,
    this.totalBytes,
    this.etaMs,
    this.detail,
  });

  @override
  int get hashCode =>
      postId.hashCode ^
      kind.hashCode ^
      startable.hashCode ^
      bytesPresent.hashCode ^
      totalBytes.hashCode ^
      etaMs.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiDeliveryEvent &&
          runtimeType == other.runtimeType &&
          postId == other.postId &&
          kind == other.kind &&
          startable == other.startable &&
          bytesPresent == other.bytesPresent &&
          totalBytes == other.totalBytes &&
          etaMs == other.etaMs &&
          detail == other.detail;
}

/// What a delivery event reports about one post.
enum FfiDeliveryEventKind {
  /// Startability changed (or the post is newly watched).
  readiness,

  /// Bytes or the known total moved without a startability change.
  progress,

  /// The store could not be read for this post; see `detail`.
  error,
}

/// One entry of the ordered focus window, including the current item.
/// `post_id` doubles as the partial-store key and the gateway `?id=`
/// value, so it must stay within `[A-Za-z0-9_-]`.
class FfiFocusItem {
  final String postId;

  /// Playback candidates in preference order (imeta url + fallbacks).
  final List<String> urls;

  /// HLS items ride in the window for correct scroll distances but
  /// are never downloaded progressively.
  final FfiMediaDelivery delivery;
  final String? sha256;
  final BigInt? sizeBytes;
  final BigInt? durationMs;

  const FfiFocusItem({
    required this.postId,
    required this.urls,
    required this.delivery,
    this.sha256,
    this.sizeBytes,
    this.durationMs,
  });

  @override
  int get hashCode =>
      postId.hashCode ^
      urls.hashCode ^
      delivery.hashCode ^
      sha256.hashCode ^
      sizeBytes.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFocusItem &&
          runtimeType == other.runtimeType &&
          postId == other.postId &&
          urls == other.urls &&
          delivery == other.delivery &&
          sha256 == other.sha256 &&
          sizeBytes == other.sizeBytes &&
          durationMs == other.durationMs;
}

/// How the engine delivers one playable media item.
enum FfiMediaDelivery { progressive, hls }

/// One exact loopback asset selected for current or adjacent-next use.
class FfiPlaybackPreparationAsset {
  final String deliveryId;
  final String representationId;
  final String assetId;
  final String playbackUrl;
  final FfiPlaybackPreparationReadiness readiness;

  const FfiPlaybackPreparationAsset({
    required this.deliveryId,
    required this.representationId,
    required this.assetId,
    required this.playbackUrl,
    required this.readiness,
  });

  @override
  int get hashCode =>
      deliveryId.hashCode ^
      representationId.hashCode ^
      assetId.hashCode ^
      playbackUrl.hashCode ^
      readiness.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPlaybackPreparationAsset &&
          runtimeType == other.runtimeType &&
          deliveryId == other.deliveryId &&
          representationId == other.representationId &&
          assetId == other.assetId &&
          playbackUrl == other.playbackUrl &&
          readiness == other.readiness;
}

/// Atomic two-player preparation window from one manager plan.
class FfiPlaybackPreparationPlan {
  final BigInt revision;

  /// The focused delivery even while no exact progressive asset exists.
  final String? currentDeliveryId;
  final FfiPlaybackPreparationAsset? current;
  final FfiPlaybackPreparationAsset? next;

  const FfiPlaybackPreparationPlan({
    required this.revision,
    this.currentDeliveryId,
    this.current,
    this.next,
  });

  @override
  int get hashCode =>
      revision.hashCode ^
      currentDeliveryId.hashCode ^
      current.hashCode ^
      next.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPlaybackPreparationPlan &&
          runtimeType == other.runtimeType &&
          revision == other.revision &&
          currentDeliveryId == other.currentDeliveryId &&
          current == other.current &&
          next == other.next;
}

/// What the native cache has proved for one exact playback asset.
enum FfiPlaybackPreparationReadiness { preparing, structuralStartable }

/// Authority and monotonic ordering for a player-preparation update.
class FfiPlayerPreparationReport {
  final String postId;
  final String representationId;
  final String assetId;
  final BigInt playerCapabilityGeneration;
  final BigInt clientEpoch;
  final BigInt attemptGeneration;
  final BigInt sequence;
  final FfiPlayerPreparationState state;
  final String? failureKind;
  final BigInt observedMonotonicUs;

  const FfiPlayerPreparationReport({
    required this.postId,
    required this.representationId,
    required this.assetId,
    required this.playerCapabilityGeneration,
    required this.clientEpoch,
    required this.attemptGeneration,
    required this.sequence,
    required this.state,
    this.failureKind,
    required this.observedMonotonicUs,
  });

  @override
  int get hashCode =>
      postId.hashCode ^
      representationId.hashCode ^
      assetId.hashCode ^
      playerCapabilityGeneration.hashCode ^
      clientEpoch.hashCode ^
      attemptGeneration.hashCode ^
      sequence.hashCode ^
      state.hashCode ^
      failureKind.hashCode ^
      observedMonotonicUs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPlayerPreparationReport &&
          runtimeType == other.runtimeType &&
          postId == other.postId &&
          representationId == other.representationId &&
          assetId == other.assetId &&
          playerCapabilityGeneration == other.playerCapabilityGeneration &&
          clientEpoch == other.clientEpoch &&
          attemptGeneration == other.attemptGeneration &&
          sequence == other.sequence &&
          state == other.state &&
          failureKind == other.failureKind &&
          observedMonotonicUs == other.observedMonotonicUs;
}

/// Native-player evidence for one exact progressive playback attempt.
enum FfiPlayerPreparationState {
  initializing,
  initialized,
  firstFrameRendered,
  failed,
  released,
}
