// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`

/// One per-post delivery update streamed to Dart.
class FfiDeliveryEvent {
  final String postId;
  final FfiDeliveryEventKind kind;
  final bool startable;
  final BigInt bytesPresent;
  final BigInt? totalBytes;
  final String? detail;

  const FfiDeliveryEvent({
    required this.postId,
    required this.kind,
    required this.startable,
    required this.bytesPresent,
    this.totalBytes,
    this.detail,
  });

  @override
  int get hashCode =>
      postId.hashCode ^
      kind.hashCode ^
      startable.hashCode ^
      bytesPresent.hashCode ^
      totalBytes.hashCode ^
      detail.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiDeliveryEvent &&
          runtimeType == other.runtimeType &&
          postId == other.postId &&
          kind == other.kind &&
          startable == other.startable &&
          bytesPresent == other.bytesPresent &&
          totalBytes == other.totalBytes &&
          detail == other.detail;
}

/// What a delivery event reports about one post.
enum FfiDeliveryEventKind {
  /// Startability changed (or the post is newly watched).
  readiness,

  /// Bytes or the known total moved without a startability change.
  progress,

  /// The store could not be read for this post; see `detail`.
  error,
  ;
}

/// One entry of the ordered focus window, including the current item.
/// `post_id` doubles as the partial-store key and the gateway `?id=`
/// value, so it must stay within `[A-Za-z0-9_-]`.
class FfiFocusItem {
  final String postId;

  /// Playback candidates in preference order (imeta url + fallbacks).
  final List<String> urls;

  /// HLS items ride in the window for correct scroll distances but
  /// are never downloaded progressively.
  final FfiMediaDelivery delivery;
  final String? sha256;
  final BigInt? sizeBytes;
  final BigInt? durationMs;

  const FfiFocusItem({
    required this.postId,
    required this.urls,
    required this.delivery,
    this.sha256,
    this.sizeBytes,
    this.durationMs,
  });

  @override
  int get hashCode =>
      postId.hashCode ^
      urls.hashCode ^
      delivery.hashCode ^
      sha256.hashCode ^
      sizeBytes.hashCode ^
      durationMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFocusItem &&
          runtimeType == other.runtimeType &&
          postId == other.postId &&
          urls == other.urls &&
          delivery == other.delivery &&
          sha256 == other.sha256 &&
          sizeBytes == other.sizeBytes &&
          durationMs == other.durationMs;
}

/// How the engine delivers one playable media item.
enum FfiMediaDelivery {
  progressive,
  hls,
  ;
}
