// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'delivery_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `emit_pass`, `emit_post`, `store_view`, `watch_delivery`
// These types are ignored because they are not used by any `pub` functions: `Pass`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `send`

/// Subscribes to per-post delivery events. Each subscription runs its
/// own watcher and first reports a readiness baseline for every
/// watched post; the stream ends when the Dart side cancels it.
Stream<FfiDeliveryEvent> ffiDeliveryEvents() =>
    RustLib.instance.api.crateApiDeliveryEventsStreamFfiDeliveryEvents();

abstract class EventOut {
  /// Returns `false` once the receiver is gone: the watcher stops.
  Future<bool> send({required FfiDeliveryEvent event});
}
