// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'network_control.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_level`, `engine_configuration`, `validated_relay_urls`
// These types are ignored because they are not used by any `pub` functions: `EngineConfiguration`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`, `from`, `try_from`

/// Starts the media engine and returns the loopback endpoint as
/// `host:port`. Download concurrency is owned by the engine's parameter
/// table and scaled by `data_usage`.
Future<String> ffiStartEngine({
  required String cacheDirectory,
  required FfiEngineConfiguration configuration,
  String? deviceIntegrationOrigin,
  required FfiDeliveryNetworkStatus initialNetwork,
}) => RustLib.instance.api.crateApiEngineControlFfiStartEngine(
  cacheDirectory: cacheDirectory,
  configuration: configuration,
  deviceIntegrationOrigin: deviceIntegrationOrigin,
  initialNetwork: initialNetwork,
);

/// Applies relay, data-usage, and progressive-storage settings without
/// restarting the engine.
Future<void> ffiSetDeliveryConfig({
  required FfiEngineConfiguration configuration,
}) => RustLib.instance.api.crateApiEngineControlFfiSetDeliveryConfig(
  configuration: configuration,
);

/// User-selected network and delivery pressure.
enum FfiDataUsageLevel { conservative, balanced, aggressive }

/// Settings shared by Nostr discovery and progressive delivery.
class FfiEngineConfiguration {
  final List<String> readRelayUrls;
  final List<String> searchRelayUrls;
  final FfiDataUsageLevel dataUsage;
  final BigInt maxStorageBytes;

  const FfiEngineConfiguration({
    required this.readRelayUrls,
    required this.searchRelayUrls,
    required this.dataUsage,
    required this.maxStorageBytes,
  });

  @override
  int get hashCode =>
      readRelayUrls.hashCode ^
      searchRelayUrls.hashCode ^
      dataUsage.hashCode ^
      maxStorageBytes.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiEngineConfiguration &&
          runtimeType == other.runtimeType &&
          readRelayUrls == other.readRelayUrls &&
          searchRelayUrls == other.searchRelayUrls &&
          dataUsage == other.dataUsage &&
          maxStorageBytes == other.maxStorageBytes;
}
