// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `apply_level`, `engine_configuration`, `relay_list`

/// Starts the media engine and returns the loopback endpoint as
/// `host:port`. Replaces `ffi_start_server`; download concurrency is
/// owned by the engine's parameter table, scaled by `data_usage`
/// (`"conservative"` / `"balanced"` / `"aggressive"`).
Future<String> ffiStartEngine(
        {required String cacheDirectory,
        required String relayUrls,
        required String dataUsage,
        required BigInt maxStorageBytes}) =>
    RustLib.instance.api.crateApiEngineControlFfiStartEngine(
        cacheDirectory: cacheDirectory,
        relayUrls: relayUrls,
        dataUsage: dataUsage,
        maxStorageBytes: maxStorageBytes);

/// Live data-usage change. `max_storage_bytes` is validated only in
/// this slice: progressive-store eviction is not enforced yet (plan
/// divergence), so the budget cannot resize a running store.
Future<void> ffiSetDeliveryConfig(
        {required String dataUsage, required BigInt maxStorageBytes}) =>
    RustLib.instance.api.crateApiEngineControlFfiSetDeliveryConfig(
        dataUsage: dataUsage, maxStorageBytes: maxStorageBytes);
