// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `tag_letter`, `with_authors`, `with_event_tags`, `with_generic_tags`, `with_search`, `with_until`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `assert_fields_are_eq`, `assert_fields_are_eq`, `clone`, `clone`, `clone`, `eq`, `eq`, `eq`, `fmt`, `fmt`, `fmt`, `from`, `try_from`

/// One verified Nostr event returned to Dart.
class FfiNostrEvent {
  final String id;
  final String pubkey;
  final int kind;
  final List<List<String>> tags;
  final String content;
  final BigInt createdAt;

  const FfiNostrEvent({
    required this.id,
    required this.pubkey,
    required this.kind,
    required this.tags,
    required this.content,
    required this.createdAt,
  });

  @override
  int get hashCode =>
      id.hashCode ^
      pubkey.hashCode ^
      kind.hashCode ^
      tags.hashCode ^
      content.hashCode ^
      createdAt.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiNostrEvent &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          pubkey == other.pubkey &&
          kind == other.kind &&
          tags == other.tags &&
          content == other.content &&
          createdAt == other.createdAt;
}

/// One Nostr REQ filter supplied by Dart.
class FfiNostrEventFilter {
  final Uint16List kinds;
  final List<String> authors;
  final List<String> eventTags;
  final List<FfiNostrTagFilter> tagFilters;
  final int limit;
  final BigInt? until;
  final String? search;

  const FfiNostrEventFilter({
    required this.kinds,
    required this.authors,
    required this.eventTags,
    required this.tagFilters,
    required this.limit,
    this.until,
    this.search,
  });

  @override
  int get hashCode =>
      kinds.hashCode ^
      authors.hashCode ^
      eventTags.hashCode ^
      tagFilters.hashCode ^
      limit.hashCode ^
      until.hashCode ^
      search.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiNostrEventFilter &&
          runtimeType == other.runtimeType &&
          kinds == other.kinds &&
          authors == other.authors &&
          eventTags == other.eventTags &&
          tagFilters == other.tagFilters &&
          limit == other.limit &&
          until == other.until &&
          search == other.search;
}

/// One case-sensitive single-letter Nostr tag filter.
class FfiNostrTagFilter {
  final String name;
  final List<String> values;

  const FfiNostrTagFilter({required this.name, required this.values});

  @override
  int get hashCode => name.hashCode ^ values.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiNostrTagFilter &&
          runtimeType == other.runtimeType &&
          name == other.name &&
          values == other.values;
}
