// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'event_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `query_filters`, `validated_filters`

Future<List<FfiNostrEvent>> ffiQueryEvents({
  required FfiNostrEventFilter filter,
}) => RustLib.instance.api.crateApiEventControlFfiQueryEvents(filter: filter);

Future<List<FfiNostrEvent>> ffiQueryEventsBatch({
  required List<FfiNostrEventFilter> filters,
}) => RustLib.instance.api.crateApiEventControlFfiQueryEventsBatch(
  filters: filters,
);
