// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'delivery_types.dart';
import 'feed_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `snapshot_update`, `watch_feed`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `send`

/// Subscribes to one open feed's snapshots.
Stream<FfiFeedUpdate> ffiFeedUpdates({required String feedId}) => RustLib
    .instance
    .api
    .crateApiFeedUpdatesStreamFfiFeedUpdates(feedId: feedId);

abstract class FeedOut {
  /// Returns `false` once the receiver is gone: the watcher stops.
  Future<bool> send({required FfiFeedUpdate update});
}
