// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `clone`, `eq`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`, `fmt`

/// The creator identity a feed row renders, including the
/// shortened-npub fallback when no metadata is known.
class FfiFeedCreator {
  final String pubkey;
  final String displayName;
  final String handle;
  final String? avatarUrl;

  const FfiFeedCreator({
    required this.pubkey,
    required this.displayName,
    required this.handle,
    this.avatarUrl,
  });

  @override
  int get hashCode =>
      pubkey.hashCode ^
      displayName.hashCode ^
      handle.hashCode ^
      avatarUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFeedCreator &&
          runtimeType == other.runtimeType &&
          pubkey == other.pubkey &&
          displayName == other.displayName &&
          handle == other.handle &&
          avatarUrl == other.avatarUrl;
}

/// Playable media of one post. `delivery` round-trips with
/// `FfiFocusItem.delivery` (`"progressive"` / `"hls"`).
class FfiFeedMedia {
  /// Playback candidates in preference order (imeta url + fallbacks).
  final List<String> urls;
  final String delivery;
  final String? sha256;
  final BigInt? sizeBytes;
  final BigInt? durationMs;
  final FfiMediaDim? dim;
  final String? blurhash;
  final String? thumbUrl;

  const FfiFeedMedia({
    required this.urls,
    required this.delivery,
    this.sha256,
    this.sizeBytes,
    this.durationMs,
    this.dim,
    this.blurhash,
    this.thumbUrl,
  });

  @override
  int get hashCode =>
      urls.hashCode ^
      delivery.hashCode ^
      sha256.hashCode ^
      sizeBytes.hashCode ^
      durationMs.hashCode ^
      dim.hashCode ^
      blurhash.hashCode ^
      thumbUrl.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFeedMedia &&
          runtimeType == other.runtimeType &&
          urls == other.urls &&
          delivery == other.delivery &&
          sha256 == other.sha256 &&
          sizeBytes == other.sizeBytes &&
          durationMs == other.durationMs &&
          dim == other.dim &&
          blurhash == other.blurhash &&
          thumbUrl == other.thumbUrl;
}

/// One assembled feed row. `post_id` is the gateway-safe id Dart hands
/// back to `ffi_update_focus` / `ffi_playback_url`; it stays stable
/// across addressable revisions of the same video.
class FfiFeedPost {
  final String postId;
  final String eventId;

  /// The Nostr kind of `event_id`. Named apart from `FfiFeedSpec.kind`
  /// (a feed shape) and `FfiDeliveryEvent.kind` (an event type); with
  /// `identifier` it completes the reference Dart's social writes
  /// address.
  final int eventKind;

  /// The addressable `d` tag, present exactly for kinds 30000-39999.
  final String? identifier;

  /// Unix seconds of the post's newest event.
  final BigInt createdAt;
  final String caption;
  final List<String> hashtags;
  final FfiFeedCreator creator;
  final FfiFeedMedia media;

  const FfiFeedPost({
    required this.postId,
    required this.eventId,
    required this.eventKind,
    this.identifier,
    required this.createdAt,
    required this.caption,
    required this.hashtags,
    required this.creator,
    required this.media,
  });

  @override
  int get hashCode =>
      postId.hashCode ^
      eventId.hashCode ^
      eventKind.hashCode ^
      identifier.hashCode ^
      createdAt.hashCode ^
      caption.hashCode ^
      hashtags.hashCode ^
      creator.hashCode ^
      media.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFeedPost &&
          runtimeType == other.runtimeType &&
          postId == other.postId &&
          eventId == other.eventId &&
          eventKind == other.eventKind &&
          identifier == other.identifier &&
          createdAt == other.createdAt &&
          caption == other.caption &&
          hashtags == other.hashtags &&
          creator == other.creator &&
          media == other.media;
}

/// One feed to open, as Dart names it. `kind` selects the shape:
/// `"main"` reads the signed-in viewer from `viewer_pubkey` (hex or
/// npub); `"hashtag"` reads the tag from `value` (leading `#`
/// optional); `"search"` reads the query from `value`, as typed;
/// `"profile"` reads every creator key from `creators` — one for a
/// profile grid, the whole follow set for the Following feed.
class FfiFeedSpec {
  final String kind;
  final String? value;
  final List<String> creators;
  final String? viewerPubkey;

  const FfiFeedSpec({
    required this.kind,
    this.value,
    required this.creators,
    this.viewerPubkey,
  });

  @override
  int get hashCode =>
      kind.hashCode ^
      value.hashCode ^
      creators.hashCode ^
      viewerPubkey.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFeedSpec &&
          runtimeType == other.runtimeType &&
          kind == other.kind &&
          value == other.value &&
          creators == other.creators &&
          viewerPubkey == other.viewerPubkey;
}

/// How far the snapshot's page got. Row counts cannot answer that — a
/// plan that resolved to nothing and a plan still in flight both show
/// zero posts — so the stage is what a pull-shaped caller waits on.
enum FfiFeedStage {
  /// A retrieval is in flight; `posts` may still grow.
  loading,

  /// Every query of the page resolved: `posts` is the whole page.
  settled,

  /// The page's primary query failed; `posts` is whatever survived.
  /// ndk parity: the Dart pipeline raises a failure here rather than
  /// serving an empty feed (ndk_nostr_video_event_query.dart).
  failed,
  ;
}

/// One feed-stream update: the feed's full ordered snapshot, newest
/// first. Snapshots replace the previous list wholesale — chosen over
/// diffs so the Dart side has nothing to reconcile; `revision` is the
/// feed store's monotonic revision for cheap deduplication.
class FfiFeedUpdate {
  final String feedId;
  final BigInt revision;
  final FfiFeedStage stage;
  final List<FfiFeedPost> posts;

  const FfiFeedUpdate({
    required this.feedId,
    required this.revision,
    required this.stage,
    required this.posts,
  });

  @override
  int get hashCode =>
      feedId.hashCode ^ revision.hashCode ^ stage.hashCode ^ posts.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFeedUpdate &&
          runtimeType == other.runtimeType &&
          feedId == other.feedId &&
          revision == other.revision &&
          stage == other.stage &&
          posts == other.posts;
}

/// Pixel dimensions from the post's imeta, when declared.
class FfiMediaDim {
  final int width;
  final int height;

  const FfiMediaDim({
    required this.width,
    required this.height,
  });

  @override
  int get hashCode => width.hashCode ^ height.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiMediaDim &&
          runtimeType == other.runtimeType &&
          width == other.width &&
          height == other.height;
}
