// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'feed_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

/// Opens one feed in the Rust feed store, starts its first-page
/// queries, and returns the feed handle every later call names.
Future<String> ffiOpenFeed({required FfiFeedSpec spec}) =>
    RustLib.instance.api.crateApiFeedControlFfiOpenFeed(spec: spec);

/// Requests one older page. Returns whether more content may exist:
/// `false` once the feed is exhausted (or unknown), `true` while a
/// page is loading or a cursor remains. `older_than_secs` overrides
/// the tracked cursor when given.
Future<bool> ffiLoadMore({required String feedId, BigInt? olderThanSecs}) =>
    RustLib.instance.api.crateApiFeedControlFfiLoadMore(
        feedId: feedId, olderThanSecs: olderThanSecs);

/// Closes the feed: its posts drop and its update streams end.
Future<void> ffiCloseFeed({required String feedId}) =>
    RustLib.instance.api.crateApiFeedControlFfiCloseFeed(feedId: feedId);
