// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'delivery_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `accept_focus`, `progressive_url`, `register_progressive`, `tracked_entries`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `clone`, `clone`, `clone`, `fmt`, `fmt`, `fmt`, `fmt`

/// Replaces the ordered focus window (items include the current one),
/// refreshes the catalog, and wakes the delivery manager. `feed_id`
/// is carried for a future multi-feed surface; one feed exists today.
Future<void> ffiUpdateFocus({required FfiFocusUpdate update}) =>
    RustLib.instance.api.crateApiFocusControlFfiUpdateFocus(update: update);

/// Loopback playback URL for one item, registering it with the
/// gateway when unknown. Downloads for a post are still driven by the
/// focus window, which includes the current item by contract. HLS
/// items are refused: HLS playback stays on the session-owning
/// `ffi_acquire_hls_playback`, so one URL scheme exists per delivery
/// kind instead of a half-working progressive URL for HLS.
Future<String> ffiPlaybackUrl({required FfiFocusItem item}) =>
    RustLib.instance.api.crateApiFocusControlFfiPlaybackUrl(item: item);

enum FfiFocusTransition { userNavigation, rosterChange, transportRescue }

/// One atomic, monotonically versioned focus write from Flutter.
class FfiFocusUpdate {
  final String feedId;
  final List<FfiFocusItem> items;
  final int currentIndex;
  final BigInt watchMs;
  final BigInt generation;
  final FfiFocusTransition transition;
  final FfiTransportRescue? rescue;

  const FfiFocusUpdate({
    required this.feedId,
    required this.items,
    required this.currentIndex,
    required this.watchMs,
    required this.generation,
    required this.transition,
    this.rescue,
  });

  @override
  int get hashCode =>
      feedId.hashCode ^
      items.hashCode ^
      currentIndex.hashCode ^
      watchMs.hashCode ^
      generation.hashCode ^
      transition.hashCode ^
      rescue.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiFocusUpdate &&
          runtimeType == other.runtimeType &&
          feedId == other.feedId &&
          items == other.items &&
          currentIndex == other.currentIndex &&
          watchMs == other.watchMs &&
          generation == other.generation &&
          transition == other.transition &&
          rescue == other.rescue;
}

class FfiTransportRescue {
  final FfiTransportRescueReason reason;
  final int rankDisplacement;
  final BigInt waitMs;

  const FfiTransportRescue({
    required this.reason,
    required this.rankDisplacement,
    required this.waitMs,
  });

  @override
  int get hashCode =>
      reason.hashCode ^ rankDisplacement.hashCode ^ waitMs.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiTransportRescue &&
          runtimeType == other.runtimeType &&
          reason == other.reason &&
          rankDisplacement == other.rankDisplacement &&
          waitMs == other.waitMs;
}

enum FfiTransportRescueReason {
  etaUnavailable,
  etaTooLong,
  deliveryFailed,
  graceExpired,
}
