// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'delivery_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `progressive_entries`, `progressive_url`, `register_progressive`

/// Replaces the ordered focus window (items include the current one),
/// refreshes the catalog, and wakes the delivery manager. `feed_id`
/// is carried for the phase-2 multi-feed surface; a single feed
/// exists today, so it is accepted but not yet interpreted.
Future<void> ffiUpdateFocus(
        {required String feedId,
        required List<FfiFocusItem> items,
        required int currentIndex,
        required BigInt watchMs}) =>
    RustLib.instance.api.crateApiFocusControlFfiUpdateFocus(
        feedId: feedId,
        items: items,
        currentIndex: currentIndex,
        watchMs: watchMs);

/// Loopback playback URL for one item, registering it with the
/// gateway when unknown. Downloads for a post are still driven by the
/// focus window, which includes the current item by contract. HLS
/// items are refused: HLS playback stays on the session-owning
/// `ffi_acquire_hls_playback`, so one URL scheme exists per delivery
/// kind instead of a half-working progressive URL for HLS.
Future<String> ffiPlaybackUrl({required FfiFocusItem item}) =>
    RustLib.instance.api.crateApiFocusControlFfiPlaybackUrl(item: item);
