// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_receiver_is_total_eq`, `assert_receiver_is_total_eq`, `clone`, `clone`, `eq`, `eq`, `fmt`, `fmt`

/// One self-contained, ordered playback sample.
class FfiPlaybackObservation {
  final String postId;
  final BigInt generation;
  final BigInt sequence;
  final FfiPlaybackPhase phase;
  final BigInt positionMs;
  final BigInt bufferedExtentMs;
  final int playbackRateMilli;

  const FfiPlaybackObservation({
    required this.postId,
    required this.generation,
    required this.sequence,
    required this.phase,
    required this.positionMs,
    required this.bufferedExtentMs,
    required this.playbackRateMilli,
  });

  @override
  int get hashCode =>
      postId.hashCode ^
      generation.hashCode ^
      sequence.hashCode ^
      phase.hashCode ^
      positionMs.hashCode ^
      bufferedExtentMs.hashCode ^
      playbackRateMilli.hashCode;

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is FfiPlaybackObservation &&
          runtimeType == other.runtimeType &&
          postId == other.postId &&
          generation == other.generation &&
          sequence == other.sequence &&
          phase == other.phase &&
          positionMs == other.positionMs &&
          bufferedExtentMs == other.bufferedExtentMs &&
          playbackRateMilli == other.playbackRateMilli;
}

/// Explicit player phases crossing the Flutter/Rust boundary.
enum FfiPlaybackPhase {
  starting,
  playing,
  networkStalled,
  paused,
  ended,
  inactive,
}
