// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';
import 'playback_types.dart';

/// Reports one ordered playback snapshot to the single delivery manager.
Future<void> ffiReportPlayback({required FfiPlaybackObservation input}) =>
    RustLib.instance.api.crateApiPlaybackControlFfiReportPlayback(input: input);

/// Returns process-lifetime playback decisions and latest accepted identity.
Future<FfiPlaybackAdmissionSnapshot> ffiPlaybackAdmissionSnapshot() =>
    RustLib.instance.api.crateApiPlaybackControlFfiPlaybackAdmissionSnapshot();
