// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'delivery_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `wait_for_change`, `watch_preparation`
// These types are ignored because they are not used by any `pub` functions: `PreparationContext`
// These functions are ignored (category: IgnoreBecauseNotAllowedOwner): `send`

/// Streams one atomic current-plus-upcoming window; cancellation drops the watcher.
Stream<FfiPlaybackPreparationPlan> ffiPlaybackPreparationEvents() => RustLib
    .instance
    .api
    .crateApiPlaybackPreparationStreamFfiPlaybackPreparationEvents();

abstract class PreparationOut {
  Future<bool> send({required FfiPlaybackPreparationPlan plan});
}
