// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'delivery_types.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `admit`, `load_candidate`, `map_report`, `report_player_preparation`, `validate_asset`
// These types are ignored because they are not used by any `pub` functions: `CandidateAsset`, `PlayerPreparationContext`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `from`

Future<void> ffiReportPlayerPreparation({
  required FfiPlayerPreparationReport input,
}) => RustLib.instance.api
    .crateApiPlayerPreparationControlFfiReportPlayerPreparation(input: input);
