// This file is automatically generated, so please do not edit it.
// @generated by `flutter_rust_bridge`@ 2.7.0.

// ignore_for_file: invalid_use_of_internal_member, unused_import, unnecessary_import

import '../frb_generated.dart';
import 'package:flutter_rust_bridge/flutter_rust_bridge_for_generated.dart';

// These functions are ignored because they are not marked as `pub`: `reset_session`, `session_generation`
// These function are ignored because they are on traits that is not defined in current crate (put an empty `#[frb]` on it to unignore): `assert_fields_are_eq`, `clone`, `eq`, `fmt`, `fmt`

/// Clears account-scoped Nostr state without stopping the media engine.
Future<void> ffiResetNostrSession({String? expectedPublicKeyHex}) =>
    RustLib.instance.api.crateApiSessionControlFfiResetNostrSession(
        expectedPublicKeyHex: expectedPublicKeyHex);

/// Typed failures from [`ffi_reset_nostr_session`].
enum NostrSessionResetError {
  engineNotStarted,
  invalidExpectedPublicKey,
  ;
}
